### ISSUE TITLE
Smoothing

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#1]
It would be nice to add a lowpass filtering capability that does not distort phase.

Splines are pretty awesome for that. 
I'd start with:
http://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.spline_filter1d.html#scipy.ndimage.spline_filter1d
or
http://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.html#scipy.interpolate.UnivariateSpline

On no account should a running mean ever be used!!!
http://mres.uni-potsdam.de/index.php/2017/02/10/better-avoid-running-means/

**Comment by CommonClimate** [comment]
One could also use AR padding as in http://github.com/CommonClimate/common-climate/blob/master/hepta_smooth.m

**Comment by CommonClimate** [comment]
Another option is the Saviztky-Golay filter: http://stackoverflow.com/questions/20618804/how-to-smooth-a-curve-in-the-right-way

Beware: the scipy implementation (http://scipy.github.io/devdocs/generated/scipy.signal.savgol_filter.html#scipy.signal.savgol_filter) uses a "mirror" boundary condition, which is not always appropriate

**Comment by khider** [comment]
@pratheekbalaji Use the Spectral class in spectral module. Make it a static method.

**Comment by khider** [comment]
@pratheekbalaji : In addition to SplineFilter from above, add lanczos filter from:

`def lanczos(x,fc,fs=1,pad=True,params=(2,1,2),padFrac=0.1):
    """Calculate weights for a low pass Lanczos filter.
​
    Args:
        - x: series to be filtered (1d NumPy array)
        - fc:  The cutoff frequency in units of time steps. (float)
​
    Output
        - the filtered series, xf
​
    Uses filter design from http://scitools.org.uk/iris/docs/v1.2/examples/graphics/SOI_filtering.html
    """
​
    t = np.arange(len(x)) # define "time" axis
​
    if (pad):
        xp,tp = tsPad(x,t,params=params,padFrac=0.1,diag=True)
    else:
        xp = x; tp = t
​
    window = max(51,len(xp)//4)  # arbitrary?
​
    order = ((window - 1) // 2 ) + 1
    nwts = 2 * order + 1
    w = np.zeros([nwts])
    n = nwts // 2
    w[n] = 2 * fc / fs
    k = np.arange(1., n)
    sigma = np.sin(np.pi * k / n) * n / (np.pi * k)
    firstfactor = np.sin(2. * np.pi * fc / fs * k) / (np.pi * k)
    w[n-1:0:-1] = firstfactor * sigma
    w[n+1:-1] = firstfactor * sigma
    wgts = w[1:-1]
​
    xpf = np.convolve(xp,wgts, 'same')
    xf  = xpf[np.isin(tp,t)]
​
    return xf`

**Comment by khider** [comment]
@CommonClimate can you send the Matlab code for this?

**Comment by CommonClimate** [comment]
For lanczos? I don't believe I have one.

**Comment by khider** [comment]
You mentioned a Matlab code last week for smoothing. That one. Or I'll take Python

**Comment by khider** [comment]
Savitzky-Golay is implemented in Pyleoclim.utils.filter.svatizky_golay.
Need to implement lanczos

**Comment by CommonClimate** [comment]
Addressed
