### ISSUE TITLE
Link all rst files to the main documentation entry page

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#100]
**Is your feature request related to a problem? Please describe.**
Not easy to get started.

**Describe the solution you'd like**
Link main landing pages to core/utils to the main Pyleoclim page

**Comment by CommonClimate** [comment]
Should be addressed by the latest index.rst, though that one won't be visible on Github until we pull Development into the main branch.

**Comment by khider** [comment]
Done in version 0.5.1
