### ISSUE TITLE
Inconsistent parameter "trend" and the index for "g" in `ar1_fit_evently()`

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#103]
In current version of `ar1_fit_evenly()`, we have:
```
ar1_mod = ARIMA(y, order = (1, 0, 0), missing='drop',trend='ct').fit()
g = ar1_mod.params[0]
```
If `g` is taken from `ar1_mod.params[0]`, then `trend` should be set to `n`; otherwise, if `trend` is set to `ct`, then `g` should be taken from `ar1_mod.params[2]`.

This bug will lead to incorrect estimation of lag-1 autocorrelation.

**Comment by fzhu2e** [comment]
Fixed by using `g = ar1_mod.params[2]`

**Comment by CommonClimate** [comment]
Thanks for documenting and fixing the problem, @fzhu2e . Can we close the issue now?

**Comment by fzhu2e** [comment]
> Thanks for documenting and fixing the problem, @fzhu2e . Can we close the issue now?

Yes, closed
