### ISSUE TITLE
Update Series.distplot() Function

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#104]
Issue: Series.displot() currently uses the seaborn function "distplot" which is deprecated and will be removed from future seaborn releases.

Fix: Replace the use of sns.distplot in Series.displot() with either "sns.displot" or "sns.histplot".

**Comment by fzhu2e** [comment]
Got "RuntimeError: Non Expected exception in `/Users/fzhu/Github/Pyleoclim_util/pyleoclim/core/ui.py:docstring of pyleoclim.core.ui.Series.distplot` line None" when generating the documentation. The previous version with `distplot()` works.

**Comment by fzhu2e** [comment]
Sorry, that was due to my old version of seaborn. It works with the latest version. Closed.
