### ISSUE TITLE
Create figure to describe Pyleoclim package structure

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#113]
**Is your feature request related to a problem? Please describe.**
Need to give potential contributors a rapid overview of how the package is organized and where to contribute

**Describe the solution you'd like**
Make a high-level conceptual figure

**Comment by CommonClimate** [comment]
@fzhu2e we have this figure in one of your notebooks, no?

**Comment by fzhu2e** [comment]
> @fzhu2e we have this figure in one of your notebooks, no?

Yes, it's in the end of https://github.com/LinkedEarth/Pyleoclim_util/blob/Development/example_notebooks/pyleoclim_ui_tutorial.ipynb
Although it's a quite old one.

**Comment by CommonClimate** [comment]
It's be great if you could update it to reflect the major Classes (Series, MultipleSeries, EnsembleSeries), or maybe a different figure?

**Comment by fzhu2e** [comment]
> It's be great if you could update it to reflect the major Classes (Series, MultipleSeries, EnsembleSeries), or maybe a different figure?

Sure. I will make one this week.

**Comment by fzhu2e** [comment]
![image](https://user-images.githubusercontent.com/1380844/108144101-cf88bd00-707d-11eb-8d8e-8ee6dc23dc45.png)
