### ISSUE TITLE
plot functions behavior differently under different environments

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#117]
With the current latest python environment, the matplotlib plot functions will display the inline figure in a Jupyter notebook, even without the explicit `plt.show()` command. This new default behavior will make Pyleoclim plotting functions plot two figures in one call, because the current plot functions in pyleoclim always call `pyleo.showfig(fig)` when `mute=False`.

**Comment by fzhu2e** [comment]
Fixed in commit e3f88359d367e05532ac39337d30262b0fe03d7c by adding `plt.ioff()` in every plotting function so that we have a consistent explicit behavior.

For instance, assume we have a `Series` object called `ts`, then `ts.plot()` will display one figure, `ts.plot(mute=True)` will not display any figure until `pyleo.showfig(fig)` is called.

**Comment by CommonClimate** [comment]
Thanks for this! It did the trick for me.
