### ISSUE TITLE
Lomb-Scargle normalization

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#131]
**Describe the bug**
The pyleoclim implementation of Lomb-Scargle, which uses Welch's Overlapping Segment Averaging, exhibits a normalization inconsistent with other methods (e.g. MTM, scipy lomb-scargle). Hypothesis: no normalization is applied in the current `pyleo.spectral.lombscargle()`, whereas there should be.

**To Reproduce**

Apply all methods to a signal of known variance

**Expected behavior**

Methods should show close scaling. 

**Clues**
We should take a page out of Scipy's book regarding normalization: https://github.com/scipy/scipy/blob/v1.6.0/scipy/signal/spectral.py#L1576

**Comment by khider** [comment]
Fixed in this commit: [e7ebf](https://github.com/LinkedEarth/Pyleoclim_util/commit/e7ebfef0df14a8fcdb3d25ce0ad51dcb1ac4e951)
