### ISSUE TITLE
plotting method for EnsembleSeries

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#133]
**Is your feature request related to a problem? Please describe.**

EnsembleSeries currently have no plot method. 

**Describe the solution you'd like**
It would be nice for an ensembleSeries to have a `plot()` method that shows "ribbons" aligned with quantiles (default = 2.5%, 25, 50, 75, 97.5). 

**Describe alternatives you've considered**
Doing so manually 
**Additional context**

![PAGES2k_LMR_GMST](https://user-images.githubusercontent.com/13760223/105440477-79119580-5c1b-11eb-8c01-6e50f1d00ef6.png)

**Comment by CommonClimate** [comment]
optionally, the method could use the concept of Highest Density region, though the package `pymc3`, though it is a heavy one that might make pyleoclim even bulkier than it already is:

`import pymc3
from scipy.stats import norm
a = norm.rvs(size=10000)
pymc3.stats.hpd(a)`

**Comment by khider** [comment]
Like the PSD method, plot() should  select some lines and plot them on top of each in the same color/half transparency to show areas of high density in the ensemble. plot_envelop() should apply to the example above.

**Comment by CommonClimate** [comment]
Good point. I'm adapting `plot_envelope()` as we speak to make it the `plot()` function for EnsembleSeries. Any opinions on the defaults for `xlabel` and  `ylabel`? The current EnsembleSeries class has very few requirements, so I am not sure what assumptions to make.

**Comment by khider** [comment]
So EnsembleSeries should have two functions:
-`plot()`: which should be the spaghettis with transparency levels
-`plot_envelope()` as shown in your example. The labels should follow what we do for `Series.plot()`.

**Comment by CommonClimate** [comment]
OK for labels. I can do the two functions as you say, though what I've learned drawing the probstack "serpent" is that export doesn't always respect transparency, so being able to plot quantiles would be definitely needed.

**Comment by CommonClimate** [comment]
b26561c
