### ISSUE TITLE
cwt outputs don't compare to wwz

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#135]
**Describe the bug**
CWT outputs and inputs don't align to wwz, resulting in erroneous amplitude.

**Comment by khider** [comment]
Examples are documented [here](https://github.com/KnowledgeCaptureAndDiscovery/autoTS/tree/master/notebooks/Methods/Wavelet%20Analysis). Torrence and Compo seems to be the better option.

**Comment by khider** [comment]
Torrence and Compo method enabled from Series.Wavelet and MultipleSeries.wavelet in [d2cf4fe](https://github.com/LinkedEarth/Pyleoclim_util/commit/d2cf4feed81180bebc42bd3566218c18046406a0). 

To do next:
- [ ] Enable asymptomatic sig testing (on top of AR1) for cwt. @jeg: Propose to use a default of `None` which will result in `AR1sim` for WWZ and `AR1asym` for cwt. 
- [ ] Enable obtaining a PSD from cwt (add this method to `Series.spectral`, `MultipleSeries.spectral`)
- [ ] Significance testing for cwt-based PSD. Again, the `signif` parameter would have to default to `None` 
- [ ] Modify `Series.summary_plot()` to allow for the `cwt` option. See #84

**Comment by CommonClimate** [comment]
- Use None as default parameter for AR1method
- [ ] Enable asymptotic signif test for MTM, Welch, Periodogram

**Comment by khider** [comment]
Implementation in [d172ee00](https://github.com/LinkedEarth/Pyleoclim_util/commit/d172ee0079f4dde08ded859cf054e136c3108110). However, there are some discrepancies between the asymptotic solution and the simulations
![cwt](https://user-images.githubusercontent.com/11758571/163630106-6a462fec-b08a-45f4-b585-3f4c76704af6.png)
![MTM](https://user-images.githubusercontent.com/11758571/163630108-cafa8da5-41a0-4628-b5b8-6ad2129cdba0.png)

**Comment by khider** [comment]
1. Code solution: default to simulations for everything. 
2. Math solution: needs exploring where the bias comes from

- [ ] Write notebook documenting the discrepancy on known, generated data.

**Comment by khider** [comment]
@alexkjames 

Summary_plot algorithm:

- method default is none: if evenly spaced, use `cwt`, if unevenly spaced, use `wwz`.
- If user asks for `cwt` on unevenly-spaced dataset, raise an error. 

Developer corner:
`cwt` doesn't have separate parameters for spectrum vs wavelet as in the case for `wwz`, so if no PSD/Scal is passed. Compute Scalogram(s) and store to estimate spectrum both for the series and AR1 benchmark.

**Comment by khider** [comment]
Default to `ar1sim` in [aa4e23a](https://github.com/LinkedEarth/Pyleoclim_util/commit/aa4e23a2dd553232a992f358582bb2268ce91af2)

**Comment by khider** [comment]
Done.
