### ISSUE TITLE
module 'pyleoclim' has no attribute 'Series' - tutorial examples fail

### ISSUE THREAD

**Issue by andrewdolman** [LinkedEarth/Pyleoclim_util#140]
When trying to follow the tutorial here:
https://nbviewer.jupyter.org/github/LinkedEarth/Pyleoclim_util/blob/master/example_notebooks/pyleoclim_ui_tutorial.ipynb

The examples fail already in the first few lines as:

AttributeError: module 'pyleoclim' has no attribute 'Series'

e.g.

```
import pyleoclim as pyleo
pyleo.Series()

```

Using pyleoclim from R via reticulate, but I don't think this can be the issue, I can access other functions from pyleo

Are the docs just out of date?

MacOS

> py_config()

python:         /Users/andrewdolman/Library/r-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/andrewdolman/Library/r-miniconda/envs/r-reticulate/lib/libpython3.6m.dylib
pythonhome:     /Users/andrewdolman/Library/r-miniconda/envs/r-reticulate:/Users/andrewdolman/Library/r-miniconda/envs/r-reticulate
version:        3.6.12 | packaged by conda-forge | (default, Dec  9 2020, 00:24:39)  [GCC Clang 11.0.0]
numpy:          /Users/andrewdolman/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.5

**Additional context**

**Comment by khider** [comment]
Which version of Pyleoclim are you using? Also Pyleoclim and its libraries are no longer compatible with Python 3.6. It needs to function under Python 3.8

When running your example above, I do get an error because you need to provide time and value.
```import pyleoclim as pyleo
pyleo.Series()
Traceback (most recent call last):

  File "<ipython-input-1-1d5766212ad3>", line 2, in <module>
    pyleo.Series()

TypeError: __init__() missing 2 required positional arguments: 'time' and 'value'```

**Comment by fzhu2e** [comment]
Hi Andrew, we haven't released the latest version yet. Please upgrade to Python 3.8 and install Pyleoclim via the Development branch: `pip install git+https://github.com/LinkedEarth/Pyleoclim_util.git@Development`

**Comment by andrewdolman** [comment]
Thank you Deborah and Feng, I may be trying to run before I can walk. I'm an R not Python user and am struggling to specify a particular version of Python and getting confused by environments, condas, minicondas etc.. I should get get the basics sorted out first.
