### ISSUE TITLE
Potential issue with Lomb-Scargle dealing with unevenly-spaced data

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#141]
When dealing with unevenly-spaced data with wide range of time spacing like the EDC record, the order of the amplitude seems offset. MTM with interpolation is closer to WWZ. See the screenshot below:
![image](https://user-images.githubusercontent.com/1380844/107823850-56affb00-6d35-11eb-8464-3eac43ff22f2.png)

It seems this issue won't occur for other unevenly-spaced data with a reasonable range of time spacing. See the screenshot below:
![image](https://user-images.githubusercontent.com/1380844/107824005-924ac500-6d35-11eb-826e-cc663eac2e82.png)

**Comment by khider** [comment]
Resolved in latest update.
