### ISSUE TITLE
Progress bar for EnsembleSeries correlations

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#142]
**Is your feature request related to a problem? Please describe.**
Chronological ensembles are typically large (n=1000) and carrying out Monte Carlo simulations on them takes time. The absence of a progress bar means that users have no way of knowing how long they'll have to wait for a result. 

**Describe the solution you'd like**
Implement a progress bar, as in the spectral significance tests

**Describe alternatives you've considered**
Watch paint dry until the result comes out

**Comment by fzhu2e** [comment]
Added in commit 1a9b057. The progress bar is turned on by default and can be muted with `correlation(..., mute_pbar=True)`.
