### ISSUE TITLE
Lomb-Scargle method returning an error for a specific series

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#143]
**Describe the bug**
The underlying spicy function fails with `ZeroDivisionError: float division`

**To Reproduce**
Use this series: https://github.com/LinkedEarth/paleoHackathon/blob/main/data/ODP846.Lawrence.2006.lpd
Then 
`import pyleoclim as pyleo
import numpy as np
d=pyleo.Lipd('/Users/deborahkhider/Documents/GitHub/paleohack_private/data/ODP846.Lawrence.2006.lpd')
psd=d.to_LipdSeries(number=2, mode='chron').standardize().detrend().interp().spectral()`

Works with n50=1, n50=4...

**Expected behavior**
To fix

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Mac OS Big Sur
 - Pyleoclim v 0.6.1b

**Additional context**

**Comment by fzhu2e** [comment]
Tested putting the `_lombscargle()` from https://github.com/scipy/scipy/blob/master/scipy/signal/_spectral.py into the `lombscargle()` of the local miniconda3/envs/pyleoenv/lib/python3.8/site-packages/scipy/signal/spectral.py, and it works fine. Without putting it, we don't have the local _spectral.py file but a `_spectral.cpython-38-darwin.so`, so I think this compiled file is somehow different from the source code, which might be related to some numerical optimization stuff.

**Comment by khider** [comment]
Opened an issue on Scipy: https://github.com/scipy/scipy/issues/13812

**Comment by khider** [comment]
Add issue to documentation.

**Comment by khider** [comment]
Happens when dt is too close to each other. nlumpy doesn't resolve the trialing digits correctly.
