### ISSUE TITLE
ReadTheDocs does not index UI methods

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#146]
**Describe the bug**
UI methods (e.g. `plot_envelope()`) are not indexed by the current documentation, instead pointing users either to the source code or to the lower-level functions, which don't have the same defaults or arguments.

**To Reproduce**
type "plot_envelope()" in the search box of https://pyleoclim-util.readthedocs.io/en/stable/index.html

**Expected behavior**
be able to find things where they belong

**Comment by khider** [comment]
Implemented a better search engine in the doc: https://pyleoclim-util.readthedocs.io/en/latest/? The UI methods now show up but not necessarily ranked first.
