### ISSUE TITLE
MultipleSeries.common_time ignores user-defined step

### ISSUE THREAD

**Issue by Mattriks** [LinkedEarth/Pyleoclim_util#152]
Hi ya,  you might remember me from [Iso2k](https://github.com/nickmckay/LiPDverse/issues?q=is%3Aissue+author%3AMattriks) 😃
I've been looking at pyleoclim, identifying a few issues, and happy to submit PRs to fix them.

**To Reproduce**
Here's an example of the issue in the title:

```python
time = np.arange(1900, 2020, step=1/12)
ndel = 200
seriesList = []
for j in range(4):
    v = colored_noise(alpha=1, t=time)
    deleted_idx = np.random.choice(range(np.size(time)), ndel, replace=False)
    tu =  np.delete(time, deleted_idx)
    vu =  np.delete(v, deleted_idx)
    ts = pyleo.Series(time=tu, value=vu,  value_name='Series_'+str(j+1))
    seriesList.append(ts)
    
ms = pyleo.MultipleSeries(seriesList)

ms1 = ms.common_time(method='interp', start=1910, stop=2010, step=1/12)
np.diff(ms1.series_list[0].time)
```

**Expected behavior**
I would expect the last line to show 1/12, since I set step=1/12.

**Comment by CommonClimate** [comment]
Fix in commit 8e69b14
