### ISSUE TITLE
cwt wavelet: amplitude scaling

### ISSUE THREAD

**Issue by Mattriks** [LinkedEarth/Pyleoclim_util#153]
**Describe the bug**
To properly show energy, the cwt amplitude plot needs to be divided by the wavelet scale ([Liu et al. 2007](https://doi.org/10.1175/2007JTECHO511.1)).  
This may also lead to a fix for #135.  Happy to submit a PR.

**To Reproduce**
Here's an example for a time series with power in the subannual-annual band:

```python
# plotwav below is my own function (with Liu scaling)
cfs = {'cmap': 'turbo'}
fig, axs = plt.subplots(1,2, constrained_layout=True, figsize=(7, 3))
Swt2.scalogram_list[1].plot(mute=True, title="Before", ax=axs[0], cbar_style={'ax': axs[0], 'pad':0.0},
xlabel="Years", contourf_style=cfs)
Swt2.scalogram_list[1].plotwav(mute=True, title="After (with Liu scaling)", ax=axs[1],
cbar_style={'ax': axs[1], 'pad':0.0}, ylabel=" ", xlabel="Years", contourf_style=cfs)
```
![wavelet](https://user-images.githubusercontent.com/18226881/116648045-78795f80-a9bf-11eb-9804-4cd93f9ce9b2.png)

**Expected behavior**
As in the "after" plot.

**Comment by khider** [comment]
Thank you. This is part of the problem with [#135](https://github.com/LinkedEarth/Pyleoclim_util/issues/135).

**Comment by CommonClimate** [comment]
Thanks @Mattriks. The Liu rescaling is a rather crude measure, and one that has a number of downsides (as the high-frequency noise shows in this example). I haven't followed the recent literature on the topic, but I would hope that in the intervening time someone has come up with a more accurate correction...

**Comment by Mattriks** [comment]
My example time series is a monthly-resolved time series from a tropical site, so it has power at the 6-month (0.5) and 3-month (0.25) scales.  The Liu scaling is consistent with the theoretical relationship between the time series variance (σ²) and the squared wavelet amplitude (|Wₙ(sⱼ)|²) (Eq. 14 in Torrence & Compo 1998): the wavelet power (properly scaled) "adds up" to the time series variance.  There should be a parallel equation for wwz (can't recall off-hand where to find), which then points the way to making the cwt and wwz amplitude plots comparable.

**Comment by khider** [comment]
Comparison to Torrence and Compo is available [here](https://github.com/KnowledgeCaptureAndDiscovery/autoTS/tree/master/notebooks/Methods/Wavelet%20Analysis). The two are very much comparable as long as we address power vs amplitude. Pyleoclim will incorporate the TC method in the next release and return amplitude for comparison. 

The plot function will allow for both power and amplitude to be plotted regardless of the method. See issue [#201](https://github.com/LinkedEarth/Pyleoclim_util/issues/201)

**Comment by CommonClimate** [comment]
`cwt` method in Pyleoclim returns a Scalogram object that contains all the necessary information to scale the amplitude as per the wishes or the user. This will not be enabled automatically in Pyleoclim, however.
