### ISSUE TITLE
Allow user to change archive type in lipd object

### ISSUE THREAD

**Issue by Myunghee13** [LinkedEarth/Pyleoclim_util#159]
**Is your feature request related to a problem? Please describe.**
in the case of archive type is unknown or guessed, default will be other but needs to change this if more information is available. 

**Describe the solution you'd like**
write a method in the lipd class to overwrite archive type in the lipd

**Comment by CommonClimate** [comment]
closing because archiveType is now part of Series (easy to update), and LipdSeries is marked for removal
