### ISSUE TITLE
Stats.py clean up

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#16]
Several functions, like corrsig and rednoise, look like they are not used and should therefore be canned to avoid confusion.

**Comment by khider** [comment]
Both are used witer inside Stats.py or in init allowing for the LiPD files wrapper

**Comment by CommonClimate** [comment]
OK. names like corr_sig and corrsig are pretty confusing.  Since you said function names need to be camelCase, maybe we should apply that convection at least?
