### ISSUE TITLE
version display 

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#163]
**Is your feature request related to a problem? Please describe.**

it is not easy to figure out the version of Pyleoclim and its dependencies from the package itself.

**Describe the solution you'd like**

Emulate how [pandas](https://note.nkmk.me/en/python-pandas-version/) handles it.

**Describe alternatives you've considered**
death by `pip freeze`

**Comment by khider** [comment]
Added to the package in commit [ab1918a](https://github.com/LinkedEarth/Pyleoclim_util/commit/ab1918a4c9a728a6ff780e0009708513b211ec46).

To try:

`import pyleoclim as pyleo`  
`pyleo.__version__`
