### ISSUE TITLE
Geographical Coordinates in Multiple Series objects

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#167]
**Is your feature request related to a problem? Please describe.**
`MultipleSeries` objects cannot presently contain any spatial information (geographic coordinates of the underlying `Series` objects). This prevents mapping for spatial decompositions like PCA, MC-PCA or MSSA.  

**Describe the solution you'd like**
Add either a `coords` field ( p x 2 array, where p is the number of series) or add `lat` and `lon` fields ,each a p-vector. 

This can manually specified as vectors, or grabbed from `LiPDSeries` objects:

```
lat=[self.lipd_ts['geo_meanLat']]
lon=[self.lipd_ts['geo_meanLon']]
```
For objects where this information is unknown/irrelevant, this can be left blank. 

**Describe alternatives you've considered**
Have decomposition methods without being able to map spatial loadings (duh)

**Comment by khider** [comment]
Pass through LiPDSeries.

**Comment by khider** [comment]
Hold off until we have a better idea of how the package will interact with pandas and xarray. Do not create customization for now.

**Comment by CommonClimate** [comment]
Solution: create a new class called `MultipleLipdSeries` that is a list of LipdSeries. The latter need lat/lon, + some ancillary stuff (DataSetName, createdBy, ...) that is easy to automate. Put all the `value` vectors as `paleoData`. 

This will enable spatial methods like PCA or MSSA.

**Comment by CommonClimate** [comment]
this is done as of #424
