### ISSUE TITLE
step_style is not described in the docs

### ISSUE THREAD

**Issue by andrebelem** [LinkedEarth/Pyleoclim_util#176]
I was using gkernel (from pyleoclim.utils.tsutils.gkernel) and trying to change step_style. However, I didn't found enough information in the docs.

link to documentation: https://pyleoclim-util.readthedocs.io/en/master/utils/tsutils/gkernel.html#pyleoclim.utils.tsutils.gkernel

Thanks in advance.

**Comment by CommonClimate** [comment]
Addressed in e24723bb8797d2524f1278e279b03b4ef21419a8
