### ISSUE TITLE
summary_plot infected by lomb-scargle periodogram

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#180]
**Describe the bug**
The PSD part of `summary_plot()` uses lomb-scargle by default; This makes no sense, as the whole point of the plot is to compare the WWZ scalogram to the WWZ PSD. 

**To Reproduce**
`ts.summary_plot()`, where `ts` is any Series object

**Expected behavior**
Correspondance between WWZ scalogram and WWZ PSD

**Screenshots**
![summary_plot](https://user-images.githubusercontent.com/13760223/140993306-df86ebc1-dffe-4718-8712-f80bfb2f5b7e.png)

**Comment by khider** [comment]
Steps for PSD/Scalogram:

1. Preprocess the timeseries (detrend/standardize). 
2. Calculate PSD using the default method as WWZ

**Comment by khider** [comment]
And don't forget to update the doc strings:)

**Comment by CommonClimate** [comment]
Fixing issue #189 first will be a great help here.

**Comment by CommonClimate** [comment]
@alexkjames with issue #189 resolved, I believe you have all the pieces to put a wwz spectrum  in `summary_plot`

**Comment by alexkjames** [comment]
Fixed with pull request #192
