### ISSUE TITLE
insufficient documentation for beta_est

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#181]
`beta_est` is a great functionality, but currently not explained well enough to be useful to first-timers. In particularly, plotting the regression line on an existing spectrum is not very intuitive until one has previous code to do this.

We could either:

-  turn the output from a dictionary to a class, with a dedicated plotting method that would superimpose the regression line on an existing PSD plot;  OR
- simply provide an example of such a plot in the docstring, like:

```
beta_res = psd_wwz.beta_est(fmin=1/100,fmax=1)
fig, ax = psd_wwz.plot(figsize=[8, 4], mute=True)
lbl = fr' EDC ($\beta=${beta_res["beta"]:.2f}$\pm${beta_res["std_err"]:.2f})'
ax.plot(1/beta_res['f_binned'], beta_res['Y_reg'], linestyle='--', color='k', linewidth=1, zorder=99,label=lbl)
ax.legend()
pyleo.showfig(fig)
```

**Comment by fzhu2e** [comment]
This issue is solved in commit 8093c42.

Now the `PSD.beta_est()` returns a new PSD object that contains a not None `PSD.beta_est_res`, which will then be used by `PSD.plot()`.

See the below snapshot for an example:
![image](https://user-images.githubusercontent.com/1380844/141042420-2451324d-29e4-44bb-b176-c0641a232bbf.png)

**Comment by CommonClimate** [comment]
This is great. Thank you!

**Comment by CommonClimate** [comment]
Would it make sense to use this feature in PaleoHack NB7? I want to make sure it's used somewhere, otherwise we will forget about it.

**Comment by fzhu2e** [comment]
> Would it make sense to use this feature in PaleoHack NB7? I want to make sure it's used somewhere, otherwise we will forget about it.

I just updated NB7: https://github.com/LinkedEarth/paleohack_private/blob/main/notebooks/PaleoHack-nb07_Model-DataConfrontationInFrequencyDomain.ipynb

The below shows how the flow is simplified with the new feature:
![image](https://user-images.githubusercontent.com/1380844/141602889-82bda9a4-c96c-4131-b88b-4f8f3e09c02f.png)

Note that if we'd like to plot two scaling regimes in the same plot, we have to do it manually through the beta dictionary as before, which could be improved but a bit time consuming for me currently (might be a good practice for Alex though...):
![image](https://user-images.githubusercontent.com/1380844/141602918-5f53f249-69b2-4d54-94cb-e35c8e4b1349.png)

**Comment by CommonClimate** [comment]
Thank you so much @fzhu2e ! This is terrific. The code for the first plot is marvelously compact, and should be of great use to others. It's totally fine if more bespoke applications require manual adjustments. @alexkjames has enough on his research plate that I don't want to have him do things who re-use value is so uncertain.

**Comment by CommonClimate** [comment]
The only thing I would add is that the docstring for `beta_est` is  still example-free. Maybe re-use the example from the `gen_ts` docstring?

**Comment by fzhu2e** [comment]
> The only thing I would add is that the docstring for `beta_est` is still example-free. Maybe re-use the example from the `gen_ts` docstring?

docstrings code examples added in commit cc1716f
![image](https://user-images.githubusercontent.com/1380844/142188626-7f911469-f9a0-4508-8cbf-9d2cc396a123.png)


Note that the return of `MultiplePSD.beta_est()` is now also modified to be a new `MultiplePSD` object, which will break old codes.
