### ISSUE TITLE
MultipleSeries option to edit/remove labels

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#184]
Make labels a property so they can also be removed, edited/easily without changing the underlying LiPD structure.

**Comment by khider** [comment]
The labels on the left hand side should be easily editable or completely turned off.

**Comment by khider** [comment]
Feature added in commit [cb8ec](https://github.com/LinkedEarth/Pyleoclim_util/commit/cb8ec0baf13abacf15f4525464e9c0a928f9e3c3).

Added a label parameters that can take the following values:

- 'auto': Default behavior, uses the label that is in the pyleoclim.Series object if present. 
- None: No labels.
- list: Custom labels passed as a list.

Usage:

```
d=pyleo.Lipd('https://wiki.linked.earth/wiki/index.php/Special:WTLiPD?op=export&lipdid=MD982176.Stott.2004')
sst = d.to_LipdSeries(number=5)
d18Osw = d.to_LipdSeries(number=3)
ms = pyleo.MultipleSeries([sst,d18Osw])
ms.stackplot(labels=['sst','d18Osw')
```

![image](https://user-images.githubusercontent.com/11758571/142498919-95612a19-faca-48de-96a0-4b60ff0f4fa1.png)

```
d=pyleo.Lipd('https://wiki.linked.earth/wiki/index.php/Special:WTLiPD?op=export&lipdid=MD982176.Stott.2004')
sst = d.to_LipdSeries(number=5)
d18Osw = d.to_LipdSeries(number=3)
ms = pyleo.MultipleSeries([sst,d18Osw])
ms.stackplot(labels=None)
```

![image](https://user-images.githubusercontent.com/11758571/142499000-719d59f4-b344-4a3d-bb5c-677efd03c5e2.png)

```
d=pyleo.Lipd('https://wiki.linked.earth/wiki/index.php/Special:WTLiPD?op=export&lipdid=MD982176.Stott.2004')
sst = d.to_LipdSeries(number=5)
d18Osw = d.to_LipdSeries(number=3)
ms = pyleo.MultipleSeries([sst,d18Osw])
ms.stackplot(labels='auto')
```

![image](https://user-images.githubusercontent.com/11758571/142499087-c2fc66ab-e5a7-4363-a20a-2a07b0390afc.png)

**Comment by CommonClimate** [comment]
Nice work @khider !
