### ISSUE TITLE
Outliers documentation

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#185]
Series.outliers() has pretty minimal documentation. No example or explanation of what its doing outside of the rather nebulous "removes outliers"

I suggest bolstering documentation since it seems like an interesting method.

**Comment by khider** [comment]
Added in [a71e6c](https://github.com/LinkedEarth/Pyleoclim_util/commit/a71e6cdc97c10a250d497bbb7de7ae6c111cf31b)
