### ISSUE TITLE
getEnsemble is broken

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#186]
**Describe the bug**
When trying to load different chron measurement tables via chronEnsembleToPaleo, pyleoclim is unable to assign the correct csvName. Believed to be an issue with the getEnsemble function in the lipd utilities.

**To Reproduce**
See attached jupyter notebook and lipd file.
[SISAL_Ensemble_LoadProblem.zip](https://github.com/LinkedEarth/Pyleoclim_util/files/7619807/SISAL_Ensemble_LoadProblem.zip)

**Expected behavior**
Should be able to load ensembles from any chron measurement table without error (assuming the correct paleo measurement table is used).

**Screenshots**
<img width="1042" alt="Screen Shot 2021-11-29 at 8 54 21 AM" src="https://user-images.githubusercontent.com/24845788/143911293-e25004d3-295d-4541-ac3d-2bb46f11827f.png">

**Comment by khider** [comment]
Fixed in [ee489e](https://github.com/LinkedEarth/Pyleoclim_util/commit/ee489ebb436d2339a27e85ab1fc63c205fbb6d11)

Added a parameter to select the chron object in addition to the table and model numbers.
