### ISSUE TITLE
Series.detrend() pathological example

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#188]
**Describe the bug**

The docstring example given for `Series.detrend()` (https://pyleoclim-util.readthedocs.io/en/master/core/ui.html?highlight=standardize#pyleoclim.core.ui.Series.detrend) is pathological:  both EMD and Saviztky-Golay put in some kind of hockey stick at the end.  

**Expected behavior**
A functional example of detrending should actually remove the trend
**Screenshots**
(see link above)

Suggestion: 

- for EMD, allow to pass an integer parameter that removes the $n$ smoothest modes, as opposed to the current default ($n=1$ in all cases)
- for Saviztky-Golay, show how to play with padding to obtain a more reasonable result. 

Defaults need not be changed; only the explanation of how to customize those defaults.

**Comment by fzhu2e** [comment]
The argument `n` is added for EMD to support removing `n` smoothest modes in commit 68479d6.

**Comment by CommonClimate** [comment]
addressed by 92ab05b5e2ddf311bf351125729ae1cd066a9d6a
