### ISSUE TITLE
Obtaining a PSD from a Scalogram directly when using WWZ

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#189]
**Is your feature request related to a problem? Please describe.**
WWZ is computationally expensive. The underlying code for PSD requires to calculate the Scalogram first. However, when one wants both, the Scalogram ends up being recalculated twice in the current interface. We should allow passing an existing Scalogram. 

**Describe the solution you'd like**
Add a parameter to Series.spectral that allows to pass the Scalogram

**Comment by CommonClimate** [comment]
Changed to high priority because it will allow to get rid of #180 instantly

**Comment by fzhu2e** [comment]
This is fixed in commit c14ed3c. Note that this won't help the significance test,
and the default parameters for WWZ spectral and wavelet analysis are different. Here's the consequence:
![image](https://user-images.githubusercontent.com/1380844/145664873-cb860833-7cbd-4630-9a75-fecea5557f47.png)

**Comment by CommonClimate** [comment]
This is perfect, thanks @fzhu2e ! I am not fussed that the spectrum looks different in this case - as you say it's using different parameters.

**Comment by khider** [comment]
Shouldn't the wavelet and PSD method use the same parameters for this particular function? Given that we plot them together?

**Comment by fzhu2e** [comment]
> Shouldn't the wavelet and PSD method use the same parameters for this particular function? Given that we plot them together?

Theoretically yes; practically, not necessarily the case. The foci of the two subplots are different, and we might want to show more evident cycles with the spectral analysis.
