### ISSUE TITLE
Share noise realization between scalogram and psd signif_tests

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#193]
Currently when significance testing is done in summary plot, the noise realizations of the PSD and Scalogram are generated separately. This is computationally intensive and problematic for research purposes. 

We should allow users to save noise realization info from Scalogram significance testing to use when running significance testing for the PSD.

This is primarily useful for the summary_plot method, but it could be useful elsewhere as well. See comments on PR #192 for additional context and instructions.

**Comment by supernova120** [comment]
Dear author, in wavelet_coherence_example.ipynb, I can't import 'Spectrum' from pyleoclim. So when I change 'Spectrum' into 'spectrum', there's no attribute named 'xwc', neither does 'plot_coherence'.

**Comment by khider** [comment]
1. We need to allow for a different number or not passing a number at all for the significance test. If `number==None`, then just use whatever is available in the exported Scalogram

**Comment by khider** [comment]
Let's add a disclaimer in the doc strings regarding the decay constant (parameter, `c`).

**Comment by khider** [comment]
This was done in the newest version. Can I close the issue? @alexkjames and @CommonClimate

**Comment by alexkjames** [comment]
This can be closed
