### ISSUE TITLE
Attribute 'xwc' not available

### ISSUE THREAD

**Issue by supernova120** [LinkedEarth/Pyleoclim_util#194]
**Describe the bug**
Dear author, in wavelet_coherence_example.ipynb, I can't import 'Spectrum' from pyleoclim. So when I change 'Spectrum' into 'spectrum', there's no attribute named 'xwc', neither does 'plot_coherence'.

**Comment by fzhu2e** [comment]
Dear supernova120, sorry for the confusion. wavelet_coherence_example.ipynb is actually an obsolete notebook.

Please refer to [this link](https://pyleoclim-util.readthedocs.io/en/master/core/ui.html#pyleoclim.core.ui.Series.wavelet) for wavelet analysis, and [this link](https://pyleoclim-util.readthedocs.io/en/master/core/ui.html#pyleoclim.core.ui.Series.wavelet_coherence) for wavelet coherence analysis.

Closing now. Feel free to reopen if needed. Thanks.

**Comment by supernova120** [comment]
Dear author, thanks for your reply, much appreciation to Pyleoclim!
