### ISSUE TITLE
Old notebooks are no longer compatible with newest version of Pyleoclim

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#198]
Some of the example notebooks no longer work with Pyleoclim. We need to update them. 

Question: Should we leave them on this repository or move them to PyleoBooks?

**Comment by khider** [comment]
Notebooks were removed as of v0.7.3. They will need to be revamped and moved to PaleoBooks

**Comment by CommonClimate** [comment]
Need to separate notebooks in at least three repos:

- [ ] create PyleoclimTutorials repo that illustrates how to access Pyleoclim functionalities via the user API (one notebook per functionality, repurposing the old example_notebooks  as much as possible).  Idea: has its own environment.yml and needs to be synced to a particular version of the code.  Updated at every major release (e.g. 0.7 to 0.8) 
- [ ] PaleoBooks scope needs be explicitly about scientific workflows enabled by Pyleoclim until 2024. (sunsetting of PaleoCube grant).
- [ ] PyleoclimPaper repo only about those 3 examples in the paper, and v1.0.0

**Comment by khider** [comment]
Need a team hackathon to create these tutorials: target data -> beginning of August.

**Comment by CommonClimate** [comment]
Model:  http://gallery.pangeo.io/repos/pangeo-data/pangeo-tutorial-gallery/xarray.html

**Comment by CommonClimate** [comment]
closing with a19e8b7acf04e16a107041e476e76b6dac9c1133. Check on status of PyleoTutorials [here](https://github.com/LinkedEarth/PyleoTutorials/projects/1)
