### ISSUE TITLE
Summary_plot no longer takes into consideration scalograms and PSD passed to it. 

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#199]
**Describe the bug**
Summary_plot no longer takes into consideration scalograms and PSD passed to it. 

**To Reproduce**

```ts_benthic.summary_plot(psd=psd_benthic_wwz,scalogram=scal_benthic_wwz, value_label = '$\delta^{18}O$')```

![image](https://user-images.githubusercontent.com/11758571/153965949-5d55f8a2-0984-48e9-a16f-94e19b42dfa7.png)

**Comment by khider** [comment]
This looks done from the tests I just fixed. Correct @alexkjames?

**Comment by alexkjames** [comment]
This is fixed @khider
