### ISSUE TITLE
Age model plot

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#2]
Needs to show only the dates (circles), together with their uncertainties (error bars). No line connecting them unless there is a ChronData table or EnsembleTable in the lipd file.

**Comment by khider** [comment]
This has been a while and trying to close some issue. Which plot were you referring to?

**Comment by CommonClimate** [comment]
Age vs depth. Raw dates + uncertainties if no model has been run. Otherwise, add samples paths from the age ensemble, and 95% credible intervals.    I think it would be a nice addition to the dashboard, but not mission-critical.

**Comment by khider** [comment]
Done in commit [#2c4b7d](https://github.com/LinkedEarth/Pyleoclim_util/commit/2c4b7d2aa869f75ed952975e1d499631a01a8ac3).
