### ISSUE TITLE
New scalogram option

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#201]
**Is your feature request related to a problem? Please describe.**
Having the option to plot amplitude or amplitude squared (power) contours when plotting scalograms would be nice.

**Describe the solution you'd like**
An argument in scalogram.plot() (could call it 'contour') to adjust whether or not amplitude or power is used.

**Describe alternatives you've considered**
Not including this functionality

**Comment by khider** [comment]
Enabled in [059c31](https://github.com/LinkedEarth/Pyleoclim_util/commit/059c31da0acc5f501589b194495da1904ae06663)
