### ISSUE TITLE
Clean up nomenclature for coherence/cross-wavelet transform

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#202]
**Is your feature request related to a problem? Please describe.**
Nomenclature in developers API is confusing and do not track to the user APIS. 

**Describe the solution you'd like**
Clean up and allow access to both coherence and xwt.

**Comment by CommonClimate** [comment]
Suggestion: mirror Grinsted's nomenclature and call `xwt` what is currently `cross_wt`  and `wtc` what is currently `wavelet_coherence`. Also, `xwt` needs to be exposed at the user API level (currently only `wwz`, and `xwc` are. )

**Comment by fzhu2e** [comment]
Hi @CommonClimate, I just took a first pass:
In `wavelet.py`,
   `cross_wt` -> `xwt`, to mirror the `xwt` function of Grinsted
   `wavelet_coherence` -> `wtc`, to mirror the `wtc` function of Grinsted
   `xwc` -> `wavelet_coherence`, a wrapper to compute wavelet coherence between two timeseries. This is the function to be called by `ui.py`

**Comment by CommonClimate** [comment]
Thank you so much @fzhu2e ! We'll review this Tuesday and let you know if it's good to close.

**Comment by khider** [comment]
@fzhu2e The doctoring for `wavelet_coherence` and `wtc` looks like it's the same function. (both says retiring cross-wavelet coherence). Can you expand on the description of why these two are different?

**Comment by fzhu2e** [comment]
> @fzhu2e The doctoring for `wavelet_coherence` and `wtc` looks like it's the same function. (both says retiring cross-wavelet coherence). Can you expand on the description of why these two are different?

Updated in commit a6c0b3

`wavelet_coherence()` now says "Return the cross-wavelet coherence of two time series."
`wtc()` now says "Return the cross wavelet coherence from two sets of wavelet coefficients."

**Comment by CommonClimate** [comment]
Thanks @fzhu2e !
