### ISSUE TITLE
Bad basemap>=1.0.7 requirements when installing from pip

### ISSUE THREAD

**Issue by brews** [LinkedEarth/Pyleoclim_util#21]
Hello! Just a heads up:

Users will get an error for your `basemap` requirement when following the [install guide](https://github.com/LinkedEarth/Pyleoclim_util#install).

Can recreate this on a clean conda environment on OSX or Linux:

    conda create --name spacemonkey
    source activate spacemonkey
    conda install python=3.6 pip
    pip install 

The last `pip` command gives:

     Could not find a version that satisfies the requirement basemap>=1.0.7 (from pyleoclim) (from versions: )
    No matching distribution found for basemap>=1.0.7 (from pyleoclim)

**Comment by brews** [comment]
Thanks for the pointer @fzhu2e!

It sounds like the package can't install all of its dependencies with `pip`, do you all have a `conda` package squirreled away somewhere to handle the installation in one go?

**Comment by fzhu2e** [comment]
Oh, we haven't tried `conda` to manager the dependencies at all due to tight schedule. Maybe it's time for me to have a try. I will let you know once I get some results. Cheers.

**Comment by brews** [comment]
@fzhu2e That would be awesome and make this much easier for end-users. Would make this much easier, especially with the compiler dependencies mentioned in #22.

Let me know if you'd like some help, I can at least get the package files setup, to get things started.

**Comment by khider** [comment]
Cartopy is no longer used and I need to add a warning in the instructions about Basemap. 

Unfortunately one of our dependencies is not on conda. Not sure if conda allows for a blend of pip and conda.

**Comment by brews** [comment]
@khider Which is not on conda? I think we could blend the two if there unless there is something *really* weird (fingers crossed).

**Comment by fzhu2e** [comment]
@brews do you have a successful example of managing dependencies with `conda`? I certainly could use some help to accelerate the process. Thanks!

**Comment by brews** [comment]
@fzhu2e @khider Let me take a swing and I'll post back with my progress.

**Comment by khider** [comment]
The LiPD utilities is not on anaconda. Fingers crossed for blending.

**Comment by brews** [comment]
@fzhu2e @khider Okay, I have a package. The package installs and it can be imported successfully. I didn't see any formal test frameworks in your code so could I have one of you guys give this a spin and be sure things are working and output looks good? Please be sure to to try any function that used f2py, just as a sanity check.

Create a fresh conda environment and install with:

    conda install pyleoclim -c sbmalev

It's packaged for py3.6 for 64-bit macOS, Windows, and Linux.  Be sure conda is configured to use conda-forge.

Thank you!

**Comment by fzhu2e** [comment]
@brews Nice, it works! Once I set `conda-forge` as the highest priority, `pyleoclim` can be installed successfully with just one `conda` command line  that you provide, and the function uses f2py works.

One minor issue is that it takes quite a while to install/re-install all the packages from the channel `conda-forge` when only part of them requires to be from `conda-forge`, which could be a headache when internet condition is not so good (e.g. during a workshop).

I am interested in the details of how to package with `conda` and write recipes of the dependencies. Could you provide some refs on this or maybe you can write a tutorial? Thanks!

**Comment by brews** [comment]
Just curious, does it work if `conda-forge` is second highest priority, below `default`. I think this is the default behavior if you just follow the conda-forge documentation and "append" the channel. Might be worth a try to see if it breaks things.

I'm not entirely sure that it's all conda-forge's fault. You could test this by clearing your cache (`conda clean --all`) and try the method above with `default` as priority 1 and `conda-forge` as priority 2. I don't think I put anything in there to explicitly say that they need to be conda-forge packages.
I don't think you'll see too much of an improvement with repeated testing. `pyleoclim` has a huge list of compiled dependencies, python dependencies, plus an entire R stack. It also depends on `lipd` which doesn't have a small footprint either (e.g. pandas, pyqt). My point being you're going to need to download these dependencies one way or another.

I'll keep hosting these packages for you guys on my anaconda channel until Friday. An official "LinkedEarth" anaconda channel - or something - might be a good idea if you go down this path.

Okay, so how do you create these packages? There are a couple ways to do it, but I actually ended up making three packages. I describe this and include my files to build the packages in the attached ZIP:

[how_brews_did_this.zip](https://github.com/LinkedEarth/Pyleoclim_util/files/2206454/how_brews_did_this.zip)

**Comment by fzhu2e** [comment]
@brews Yes. Setting `conda-forge` as the second priority helps! For R stack, they are not essential for `pyleoclim`. We recommend users to install R via CRAN instead of `conda` so that they will share the same library path, so I won't put them as the dependency of `pyleoclim`, only `rpy2` is required. I will checkout your attached file. Thanks!

**Comment by fzhu2e** [comment]
@brews  Great tutorial! I've managed to upload a build to my personal channel and it works well. Anaconda.org is now temporarily forbidding new user registration and once it's back, we will create an official account to host pyleoclim on `conda`. Thanks again for the help!

**Comment by CommonClimate** [comment]
Making pyleoclim easy to install is a high priority, and I am glad than more competent people than I are looking into it. I must say that conda's process confuses me. Just yesterday I was trying to update to the latest version of seaborn (0.9.0), which is available on pip but not conda (still stuck at 0.8.1). If offsets between versions are likely to create some kind of issue, it is particularly important that we give users clear directions on which way to install, or at least document the potential pitfalls. Sounds like you guys are on the right track for this. Thank you!

**Comment by brews** [comment]
[`conda-forge` has posted a 0.9.0 version of seaborn](https://anaconda.org/conda-forge/seaborn), I don't know if you've checked with them, @CommonClimate.

This brings up a good point. If you guys do update installation documentation, be sure to mention that users should setup for use with `conda-forge`. You all have several packages that depend on their builds.
