### ISSUE TITLE
Define or backlink "paleoclimate"

### ISSUE THREAD

**Issue by capsulecorplab** [LinkedEarth/Pyleoclim_util#211]
A definition, if not a [backlink](https://en.wikipedia.org/wiki/Backlink) to a page on paleoclimateology (s.a., https://www.ncdc.noaa.gov/news/what-paleoclimatology), would be a useful for non-subject matter experts reading the documentation

**Comment by CommonClimate** [comment]
Thanks for pointing out the omission. We're curious how you got to this package (if you're not, as seems obvious, a paleoclimatologist) and what you do with it.

**Comment by capsulecorplab** [comment]
> Thanks for pointing out the omission. We're curious how you got to this package (if you're not, as seems obvious, a paleoclimatologist) and what you do with it.

General interest in open-source tools accessible/useful to citizen scientists. (Prior to March 2020) I used to run a meetup group, called `code_for_space`, in Pasadena for community members interested in enhancing their software development experience by contributing to open source projects in space science/tech.

I also know @khider through @startrekthefleet :vulcan_salute:
