### ISSUE TITLE
Data structures link in README redirects to broken page

### ISSUE THREAD

**Issue by capsulecorplab** [LinkedEarth/Pyleoclim_util#212]
**Describe the bug**
Data structures link in README redirects to broken page

**To Reproduce**
1. Go to [README.md](https://github.com/LinkedEarth/Pyleoclim_util/blob/master/README.md)
2. Click on [data structures](https://pyleoclim-util.readthedocs.io/en/stable/core/ui.html)
3. See error

**Expected behavior**
Page should not be broken

**Screenshots**
![Screenshot from 2022-03-07 21-11-49](https://user-images.githubusercontent.com/14095576/157164685-14f70c1e-c835-4017-98d2-aad24725c532.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version [97.0.2](https://www.mozilla.org/en-US/firefox/97.0.2/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-desktop&utm_campaign=about-dialog)

**Comment by khider** [comment]
Fixed on the development brach in [22c2ac2](https://github.com/LinkedEarth/Pyleoclim_util/commit/22c2ac2e532aa564d80adf833d2a738fb479f7a2). Push to Master at next release.
