### ISSUE TITLE
sklearn incompatibility

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#214]
**Describe the bug**
Pyleoclim is no longer compatible with sklearn. Using sklearn 1.0:
```
38 from sklearn.cluster import DBSCAN
39 import matplotlib.pyplot as plt
.....
ModuleNotFoundError: No module named 'sklearn.cluster'
```
Last version that worked was 0.24.2

**To Reproduce**
`import pyleoclim as pyleo` when sklearn is > 0.24.2

**Expected behavior**
no error

**Recommendations**
- in the immediate term, environment.yml should list sklearn =  0.24.2
-  for the future, figure out what has changed in sklearn and make pyleoclim compliant with 1.0 topology

**Comment by khider** [comment]
I cannot reproduce this error after a clean install of Pyleoclim in its dedicated environment. sklearn=1.0.2 was installed in the process:

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/11758571/158642104-28655679-981c-49d5-b570-60d7b6c97eaa.png">

Can you create a new environment following instructions and retest?
