### ISSUE TITLE
Broken links on the "Tutorials" doc page

### ISSUE THREAD

**Issue by jypeter** [LinkedEarth/Pyleoclim_util#216]
I have just noticed that 2 links on the [Tutorials](https://pyleoclim-util.readthedocs.io/en/master/tutorials.html) doc page are broken:

* link from _illustrated through this **Jupyter Notebook**_: https://nbviewer.jupyter.org/github/LinkedEarth/Pyleoclim_util/blob/master/example_notebooks/pyleoclim_ui_tutorial.ipynb
* link from _is provided in **this notebook**_: https://nbviewer.jupyter.org/github/LinkedEarth/Pyleoclim_util/blob/master/example_notebooks/plot_styles.ipynb

**Comment by CommonClimate** [comment]
Thanks Jean-Yves for pointing out the bugs. 

@khider was the idea to move those notebooks to PaleoBooks? As far as I am concerned, those two notebooks belong in the pyleoclim repo.

**Comment by CommonClimate** [comment]
Update: there is now a [new repository]( https://github.com/LinkedEarth/PyleoTutorials) for Pyleoclim tutorials, so the package itself is not as bulky to install, and so we can create myBinder repositories that are tied to particular software versions. 

The team will create these tutorials in August 2022. You may check on status [here](https://github.com/LinkedEarth/PyleoTutorials/projects/1), and add suggestions for tutorials as well.

**Comment by CommonClimate** [comment]
All tutorials (and many more) have been moved to https://github.com/LinkedEarth/PyleoTutorials, tested and released

**Comment by jypeter** [comment]
Nice tutorials @CommonClimate !

Now I'm wating for a conda based installation of `pyleo`, instead of pip (https://github.com/LinkedEarth/Pyleoclim_util/discussions/205)

**Comment by CommonClimate** [comment]
Thanks Jean-Yves. Actually, tutorials got even nicer: http://linked.earth/PyleoTutorials/intro.html. I'll reply to the other issue in a separate thread.
