### ISSUE TITLE
Function for wavelet_coherence

### ISSUE THREAD

**Issue by Patty-Lyn** [LinkedEarth/Pyleoclim_util#217]
I am trying to use the wavelet_coherence function to make the wavelet coherence analysis, but when I read the tutorial, I found it a little bit confusing about the change of ntau and the tau vector explicitly. May I ask how it works for these two settings? And also, how can I change the color of the plot? Thank you.

**Comment by khider** [comment]
1. Do you mean passing `ntau` and `tau` explicitly to the function or how to choose them? If the former , the parameters are exposed. The later: `tau` is essentially the evenly-spaced representation of the time axis. So you can pass whatever makes sense for your timeseries as long as it is evenly spaced. For instance if your series spans the 1800-2000CE, then you may choose to pass a `tau` as [1800,1850,1900,1950]. One thing to keep in mind is that the longer the `tau` vector is, the longer it will take to compute the coherence. 

`ntau` is a shortcut to create that vector by just giving the number of points you want in the `tau` vector. So if you set `tau` to 4 in the previous example, you'll get the same underlying `tau`. If you're not sure what to use, leave the parameters as `None` and Pyleoclim will try to figure out for you. 

2. Change the color: The underlying function is [matplotlib.contourf](https://matplotlib.org/3.5.0/api/_as_gen/matplotlib.pyplot.contourf.html). You can pass all the parameters in that function from the `contourf_style` parameter. The easiest would be `contours_style={'camp':'viridis'}`. You can check the various colormap [here](https://matplotlib.org/3.5.1/tutorials/colors/colormaps.html).

**Comment by Patty-Lyn** [comment]
HI, thank you for the reply. I have solved the problem. I also have two questions. One is for the significance level, while I am computing the significance level for the spectrum analysis, as an example: MTM or Welch. I found the significance plot is different from what I found from the paper, it should be going down with as the period going down, but the significance plot is fluctuating. And also, I found that there is only one label shows in Y-axis, how can I set the correct label and ticks for the y-axis?

**Comment by CommonClimate** [comment]
Hi Patty, 
this is starting to leave the realm of GitHub issues, which are to document, well, _issues_ (or possibly enhancements) with the code. In this case, our code appears to work as intended, so you're just asking for help on how to best use it. For this, you can either join our Slack community workspace, or our Discourse forum.  Just make a post in the [Software category](https://discourse.linked.earth/c/software/), tag it with `pyleoclim`, and you will be setting an example for generations of users to come.

Either here or there, you will need to explain what you mean by "the paper". A URL would be nice!  I'm also unclear why you want two y axes. What are you trying to do? This is most likely a [Matplotlib question](https://matplotlib.org/3.5.1/gallery/subplots_axes_and_figures/two_scales.html).  See you on discourse!
