### ISSUE TITLE
Remove WWZ-only parameters from API calls

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#219]
**Is your feature request related to a problem? Please describe.**
Currently, parameters like `ntau` are passed at the API level of `Series.wavelet()` but only apply to `wwz`, not `cwt`

**Describe the solution you'd like**
Pass those arguments in a settings dictionary instead.

**Comment by CommonClimate** [comment]
- [ ] Remove ntau from Series.wavelet() call
- [ ] Remove ntau from Series.coherence() call
- [ ] Remove ntau from MultipleSeries.wavelet() call
- [ ] Scalogram objects, MultipleScalogram objects and Coherence objects still need ntau (possibly None)
- [ ] Check whether JSON utils need updating. If so, update.

**Comment by CommonClimate** [comment]
Items 1-3 addressed in 6e488f0c840c32df4a1958f3b4083b2e1126a663.  
Item 4 appears to be a non-issue, since Scalograms and Coherence objects take `time=wave_res.time`, not tau (much less ntau). 
 Item 5 is outside my scope so I'm going to let @khider have fun with that...

**Comment by khider** [comment]
I just redesigned the utils and pushed to development. Removal of tau from the args should not be a problem with the new redesign. However, waiting on the merge for test

**Comment by CommonClimate** [comment]
Good to hear. The proof will be in the pudding...

**Comment by CommonClimate** [comment]
Addressed by 6e488f0c840c32df4a1958f3b4083b2e1126a663.
