### ISSUE TITLE
Cant find @rpath/libiomp5.dylib ref from pyleoclim/f2py_wwz.cpython-36m-darwin.so 

### ISSUE THREAD

**Issue by brews** [LinkedEarth/Pyleoclim_util#22]
Hello again!

If I work around Issue #21 by installing basemap from conda, I can open a python shell or ipython or what have you and run:

    import pyleoclim as pyleo

At this point I'm super excited for the wave of paleo awesomeness that is about to hit me. But instead I get:

    ~/miniconda/envs/spacemonkey/lib/python3.6/site-packages/pyleoclim/__init__.py in <module>()
         29 from pyleoclim import SummaryPlots
         30 from pyleoclim import Plot
    ---> 31 from pyleoclim import Spectral
         32 from pyleoclim import Stats
         33 from pyleoclim import Timeseries

    ~/miniconda/envs/spacemonkey/lib/python3.6/site-packages/pyleoclim/Spectral.py in <module>()
         34 
         35 if sys.platform.startswith('darwin'):
    ---> 36     from . import f2py_wwz as f2py
         37 
         38 '''

    ImportError: dlopen(/Users/notarealuser/miniconda/envs/spacemonkey/lib/python3.6/site-packages/pyleoclim/f2py_wwz.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libiomp5.dylib
      Referenced from: /Users/notarealuser/miniconda/envs/spacemonkey/lib/python3.6/site-packages/pyleoclim/f2py_wwz.cpython-36m-darwin.so
      Reason: image not found

And the library is not imported. Looks like it might be an issue with f2py needing an Intel lib.... I thought it could be something with MKL or GDAL...

Installing MKL from conda and then reloading the shell and importing pyleoclim gives me:

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-2828cd9a80d8> in <module>()
    ----> 1 import pyleoclim as pyleo

    ~/miniconda/envs/spacemonkey/lib/python3.6/site-packages/pyleoclim/__init__.py in <module>()
         32 from pyleoclim import Stats
         33 from pyleoclim import Timeseries
    ---> 34 from pyleoclim import RBchron
         35 
         36 

    ~/miniconda/envs/spacemonkey/lib/python3.6/site-packages/pyleoclim/RBchron.py in <module>()
         13 import pandas as pd
         14 import datetime
    ---> 15 import rpy2.robjects as robjects
         16 from itertools import chain
         17 from rpy2.robjects.packages import importr

    ~/miniconda/envs/spacemonkey/lib/python3.6/site-packages/rpy2/robjects/__init__.py in <module>()
         14 import itertools
         15 from datetime import datetime
    ---> 16 import rpy2.rinterface as rinterface
         17 import rpy2.rlike.container as rlc
         18 

    ~/miniconda/envs/spacemonkey/lib/python3.6/site-packages/rpy2/rinterface/__init__.py in <module>()
         49 del(os)
         50 
    ---> 51 from rpy2.rinterface._rinterface import (baseenv,
         52                                          emptyenv,
         53                                          endr,

    ImportError: dlopen(/Users/notarealuser/miniconda/envs/spacemonkey/lib/python3.6/site-packages/rpy2/rinterface/_rinterface.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
      Referenced from: /Users/notarealuser/miniconda/envs/spacemonkey/lib/python3.6/site-packages/rpy2/rinterface/_rinterface.cpython-36m-darwin.so
      Reason: Incompatible library version: _rinterface.cpython-36m-darwin.so requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0

I wasn't able to get around this by updating with packages on the conda-forge repos, either. So, there is still a dependency that not being taken care of?

**Comment by fzhu2e** [comment]
Hi Brews,

Yes. The `f2py` library is compiled by Intel compilers, and `mkl` is usually installed by `conda` automatically when one installs `numpy` via `conda`.

With respect to the issue of `rpy2`, just install it via `pip install rpy2` (also see https://fzhu.work/blog/python/python-dev-env-for-earth-scientists.html).

Please let me know if this solves the problem. Thanks!

**Comment by brews** [comment]
Yeah. That did it. `rpy2` was the needed dependency. Thanks again, @fzhu2e.

If someone else runs into this in the future: I thought `pip` would have gotten `rpy2` with the initial `pip install pygeoclim` but I had to do it with `conda`. macOS also needed a JRE install. Using homebrew/cask for Java 8 worked fine. On Ubuntu the repo java worked fine.

Thanks again, really appreciate the fast response.
