### ISSUE TITLE
Housekeeping project

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#221]
we need to do some housekeeping on Pyleoclim to automate more functionalities as well as close some of our APIs so the code doesn't load in a circular fashion.

It's a boring task that would be made a lot better with a hackathon. 

Let's talk about May availability for a one-day "let's clean up Pyleoclim" meeting.

**Comment by khider** [comment]
For documentation, we can use automodule while enumeration the members in an summary 1st document for the APIs. Each module can then have its own 1st with all functions. This will be faster down the line. 

We do need to redesign the text at the top of each module since it gets incorporated into the doc. 

Therefore, we first need to decide on developer APIs before doc.

**Comment by CommonClimate** [comment]
I believe this issue can be closed. @khider do you want to do the honors?

**Comment by khider** [comment]
Of course!
