### ISSUE TITLE
Clean up parameters for `common_time`

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#222]
**Is your feature request related to a problem? Please describe.**
Right now, we have two parameters that are described in almost the same exact way: `step_style` and `common_step`

**Describe the solution you'd like**
Either better describe the difference between the two or remove one

**Comment by CommonClimate** [comment]
Resolved by [7b27cb2](https://github.com/LinkedEarth/Pyleoclim_util/commit/7b27cb265917580b8ce97b9535c84049049cf66a)

**Comment by CommonClimate** [comment]
Happy to report that issue is solved. The XWT and WTC with CWT option, however, is still in the works.
