### ISSUE TITLE
Lomb-Scargle does not standardize the series automatically

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#235]
**Describe the bug**
The current Lomb-Scargle method assumes that the series has been standardized.
But users may forget that assumption and get wrong result in some cases.
If it's a required assumption, why not do it for the users?

**To Reproduce**
1. Unzip the attached file: [tos.nc.zip](https://github.com/LinkedEarth/Pyleoclim_util/files/9160961/tos.nc.zip)
2. Run the below code:
```python
import xarray as xr
import pyleoclim as pyleo

da = xr.open_dataarray('tos.nc')
ts = pyleo.Series(time=da.year, value=da.values, label='iCESM tos')
psd = ts.spectral().beta_est()
psd_std = ts.standardize().spectral().beta_est()
fig, ax = psd.plot()
fig, ax = psd_std.plot()
```

**Expected behavior**
The scaling exponent should be small. WWZ says around 0.15.

**Screenshots**
<img width="643" alt="image" src="https://user-images.githubusercontent.com/1380844/180262219-b83a549d-d39c-4375-b45f-ec4585b5b72b.png">

**Comment by khider** [comment]
We had that discussion a while back. At the time, you suggested that we should have it as False and tell the users to use the standardize function in the chaining rather than pre-process in the black box. To be fair, all the methods except wwz requires the standardization.

**Comment by fzhu2e** [comment]
> We had that discussion a while back. At the time, you suggested that we should have it as False and tell the users to use the standardize function in the chaining rather than pre-process in the black box. To be fair, all the methods except wwz requires the standardization.

Then perhaps we need to add a warning message if the series is not standardized. 

Also, I find in the case with the colored noise generated with the utils, it yields the correct answer even if I scale the series (modify the mean and variance). I wonder in what cases it will cause the similar problem in the iCESM tos case.

**Comment by khider** [comment]
is iCESM evenly-spaced? I wouldn't use Lomb-Scargle to do any scaling. It has a known bias in the slope.

**Comment by khider** [comment]
Set everything back to True. 
1. Documentation: explicitly say that we're standardizing + explain how to set to False
2. Print a warning on Standardize

**Comment by khider** [comment]
Done in [0d59b5](https://github.com/LinkedEarth/Pyleoclim_util/commit/0d59b5c52d84da162a598397f97bb75475c2e7a8)
