### ISSUE TITLE
Update MTM documentation to show defaults value

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#241]
Update the MTM documentation to reflect the default values for NW and appropriate choices.

**Comment by CommonClimate** [comment]
I added this to the documentation of `Series.spectral()` but we now have a new problem: all other methods have adjustable parameters, which we also need to explain and demonstrate how they can be changed.  How should we do so?

**Comment by khider** [comment]
I think we should not have this in the doc, but rather point to the tutorial. Or have it under each functions rather than Series.Spectral

**Comment by CommonClimate** [comment]
"I think we should not have this in the doc, but rather point to the tutorial."  Then why call the issue "Update MTM documentation..."? ;-)

I did consider updating the mtm function docstrings, but I think the spectral() docstring should show how to customize the calls via `settings`, as this is something I still have a hard time with as a developer, so I can't imagine users will have an easy time of it. That is, having to look up the notation of a parameter in the underlying function and trying it out in dictionary form  can be tedious. I think users will be grateful for (terse) pointers to customizations.

**Comment by khider** [comment]
Because the doctoring didn't even mention which values of NW would be appropriate nor what the parameters would do.

So I would have 1 example in series.spectral on how to use settings for one of the functions. And if you want to put examples of the effect then put it with the underlying functions. but again, this is more a tutorial than pure doc.

**Comment by CommonClimate** [comment]
Even if we don't generate a new figure for each customization, there would no harm in saying: "This method is controlled by the parameter P, which means ____ . To change it, pass settings = {'P": value} to `spectral()` "

**Comment by CommonClimate** [comment]
I just don't see the point of a documentation that only shows defaults

**Comment by CommonClimate** [comment]
Case in point: the `Series.wavelet()` documentation shows how change the mother wavelet, for instance.

**Comment by khider** [comment]
Added good choice values for NW in [0d59b5](https://github.com/LinkedEarth/Pyleoclim_util/commit/0d59b5c52d84da162a598397f97bb75475c2e7a8(

**Comment by khider** [comment]
Done in [d61524](https://github.com/LinkedEarth/Pyleoclim_util/commit/d615244b771c7ab711c6b4d5db28ba7d6200d2dc)
