### ISSUE TITLE
Fix the summary_plot y-axis for the PSD

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#243]
The axis between the PSD and wavelet plot is offset. Could be fixable through gridspec.

**Comment by CommonClimate** [comment]
addressed by b87659e2f2753ac0bc83258c2f1b94dac7375d76

**Comment by khider** [comment]
Add to rework the fix for version 3.6.0 of Matplotlib. I also changed the labels to read 'WWZ PSD' instead of 'PSD from WWZ' in commit [0ea6751](https://github.com/LinkedEarth/Pyleoclim_util/commit/0ea6751825040388feb5848f7bf3b0877ab5264f)
