### ISSUE TITLE
Can't pass ax object to modeplot

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#245]
**Is your feature request related to a problem? Please describe.**
It's useful to be able to pass your own ax objects to plotting functions if you want to assemble a custom plot

**Describe the solution you'd like**
Be able to pass an ax object to modeplot and have modeplot plot on that axis

**Describe alternatives you've considered**
Don't implement this

**Comment by CommonClimate** [comment]
`ax` was removed from parameters as this is already a large compound figure, meant to be used for exploratory analysis. Can revisit later if there is a need for this feature.
