### ISSUE TITLE
Gkernel runtime warning message

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#247]
**Describe the bug**
Runtime warning message about invalid value encountered in double scalars when applying .gkernel() to the seawater d18O  timeseries from MD982181.Khider.2014.lpd. The method still executes, but a warning does occur.

**To Reproduce**
Load the seawater d18O timeseries from MD982181.Khider.2014.lpd and apply .gkernel() with all defaults. The relevant LiPD file can be found in the PyleoTutorials data folder if necessary.

**Expected behavior**
No warning message

**Screenshots**
See attached screenshot for full warning message.

<img width="678" alt="Screen Shot 2022-08-15 at 10 08 15 AM" src="https://user-images.githubusercontent.com/24845788/184682476-76ad4c2e-40c3-48a1-9d98-c54abcba685c.png">

**Comment by CommonClimate** [comment]
Proposed solution: https://www.statology.org/runtimewarning-invalid-value-encountered-in-double_scalars/

**Comment by CommonClimate** [comment]
@alexkjames is this still an issue? If not, let's close.

**Comment by alexkjames** [comment]
@CommonClimate Just re-ran with the current dev branch of pyleoclim and it looks like its fixed. Not sure how exactly, must have been something I changed when I re-did gkernel. Closing with this comment
