### ISSUE TITLE
Highlighting intervals

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#255]
**Is your feature request related to a problem? Please describe.**
Attending talks a ICP, I am reminded that many paleo folks like to highlight intervals (e.g. LGM, YD, etc) on timeseries plots. We should support an easy way to do that. 

**Describe the solution you'd like**
In order not to burden `Series.plot()` or `MultipleSeries.plot()`, introduce a method called `highlight_interval()` attached to Matplotlib Axes, with the following UI:
`ax.highlight_interval(time_bnds = [start_time, end_time], color = 'silver', alpha = 0.3, label = None, label_loc = 'bottom'), label_size=8) `

**Describe alternatives you've considered**
at least provide a PyleoTutorial for how to do this manually

**Comment by CommonClimate** [comment]
An extension of that would be to add [Marine Isotope Stages](http://railsback.org/Fundamentals/SFMGSubstages01.pdf) to a timeseries plot. The dates can be found [here](https://en.wikipedia.org/wiki/Marine_isotope_stages#Stages).

**Comment by jordanplanders** [comment]
Pull request [here](https://github.com/LinkedEarth/Pyleoclim_util/pull/509)
