### ISSUE TITLE
Pyleoclim doesn't know how to deal with 'BP' as a time unit

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#259]
**Describe the bug**
When 'BP' gets passed as a time unit, series.convert_time_unit() seems to quietly make some very big assumptions about what this means. While 'BP' isn't technically a time unit, it does seem like something used colloquially often enough that pyleoclim should have some protocol it follows when it crops up.

**To Reproduce**
Create a series with time units of 'BP' and try converting it into 'yr BP'

**Expected behavior**
An error should appear and the process should not complete. Could also consider a warning, but I think an error is probably more appropriate.

**Comment by CommonClimate** [comment]
@alexkjames I support throwing an error. Can you implement that as we discussed on Slack? Thanks!

**Comment by alexkjames** [comment]
Addressed in ca471128229efa092bec7263b38002cc4206cfd9
