### ISSUE TITLE
MultipleSeries.stackplot has plotting.showfig call

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#261]
**Describe the bug**
MultipleSeries.stackplot still uses plotting.showfig despite showfig being removed from the plotting utilities

**Expected behavior**
Should be replaced with something else or removed

**Comment by alexkjames** [comment]
I think its fine just to delete this line of code but I wanted to document this in case I'm wrong and break stackplot somehow

**Comment by CommonClimate** [comment]
How is this not returning an error?

**Comment by alexkjames** [comment]
its hidden behind an if else statement, so if you pass fig,ax = ms.stackplot there's not problem. it should return an error if you just call ms.stackplot

**Comment by alexkjames** [comment]
fixed in: e11082f648b95143863791f67af53c9c673e180a
