### ISSUE TITLE
Logkeeping

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#265]
**Is your feature request related to a problem? Please describe.**
There is currently no way to track the various transformations applied to a timseries, and to reverse most of these transformations (except centering)

**Proposed Solution**
Introduce a `log` property to `Series` as a tuple, whichhas several advantages:
- tuples are immutable, which prevents accidental overwriting/deletion 
- updating is easy
- the property `Series.log` display` nicely without having to do anything

**How to implement**

For each transformation function:
- add `keep_log = True` to the argument list
- add this to the docstring:
```keep_log : Boolean
            if True, adds [XYZ] and method parameters to the series log. 
```

- before the function's return statement, add a clause like this:
```if keep_log == True:
            new.log = new.log + ({len(new.log)+1:'center', 'args': timespan, 'previous_mean': ts_mean},)
```

(note the parentheses and comma to properly add to the original tuple. 
- add an example of use to the docstring example, particularly if there is something that was taken out and can be put back. 

**Transformations in which to implement a log**
- [x] bin
- [x] center
- [x] clean
- [x] convert_time_unit
- [x] detrend
- [x] fill_na
- [x] filter
- [x] gaussianize
- [x] gkernel
- [x] interp
- [x] outliers 
- [x] sort
- [x] standardize

Not sure:
- segment

**Comment by CommonClimate** [comment]
update: all done except outliers: 81c79a96e51fff3fc15cf811f5fceb37976fa5ac

**Comment by khider** [comment]
Added the log for outliers in [62fbb24](https://github.com/LinkedEarth/Pyleoclim_util/commit/62fbb2490cebe9f357ba36a9f1ffea84cbae9e19).

Also added a test for this new functionality.

**Comment by CommonClimate** [comment]
FYI, that commit only adds `pangeapy` to environment.yml

**Comment by CommonClimate** [comment]
I’ve verified that the 13 methods included in the list are included in the unit tests, with `keep_log=True` passed as an argument when a transformation is applied. That is, for those transformations that have a unit test: exceptions are fill_na(), convert_time_unit() and sort().  I don’t think those unit tests are in dire need of being created, so I am going to close the issue.
