### ISSUE TITLE
Series.segment returning wrong object type

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#266]
**Describe the bug**
If the segment() method is used on a LipdSeries object and gaps are detected, the subsequent MultipleSeries object contains Series objects instead of LipdSeries objects.

**To Reproduce**
Create a LipdSeries object with gaps in the time axis and apply .segment().

**Expected behavior**
The MultipleSeries object produced by .segment() should contain the same type of object (and associated metadata) as the one it was applied to.

**Notes**
This might be a good place to apply the new log functionality, as changes in the time axis of the LipdSeries object will go unrecorded in the attached lipd_ts attribute.

**Comment by khider** [comment]
Since we may change the architecture of LipdSeries, this may no longer be an issue. Wait until we learn more about how we want to handle data coming from a LiPD file

**Comment by CommonClimate** [comment]
@alexkjames did you end up resolving this?

**Comment by alexkjames** [comment]
@CommonClimate No, still waiting to hear regarding the fate of LipdSeries objects (see deborah's comment above)

**Comment by CommonClimate** [comment]
revisit after #270 is closed
