### ISSUE TITLE
Running without an IDE

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#271]
**Is your feature request related to a problem? Please describe.**
I usually run python on a linux machine and I run ipython in its own window. That is, I do not use spyder. To look at the variable list, I use whos. When I type whos, I get a long list of the time series - every line in the time series is printed to the screen as best I can tell. I dont know if other variables are listed because my data is so long, several 100 lines, its too much time to scroll to the top. 

**Describe the solution you'd like**
I would like whos to just list the variables, including the pyleoclim Series, with their length, type, etc.

**Comment by CommonClimate** [comment]
Any idea how to accommodate this need? My first instinct would be: give Spyder a try!

**Comment by khider** [comment]
I'm not sure there is anything we can do about this. There is view now but you would need to know the name of the variables.

**Comment by CommonClimate** [comment]
I forgot all about the context of this issue. Who did it originate from? We might need to just close it.
