### ISSUE TITLE
Flipping Series

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#273]
**Is your feature request related to a problem? Please describe.**
At present, it is not particularly easy to flip either the time or value vectors in a `Series` object (and children). 

**Describe the solution you'd like**
Implement a `flip()` method on the `Series` and `MultipleSeries` classes. By default, this would multiply the `value` vector by -1. Optionally, this could also be used to flip the time axis, though we'd need to be smart about conversions (e.g. BP to CE). This could be handled internally in `convert_time_unit()`, or in a new function `convert_time_representation()`, which would deal with all 3 parameters (units, origin, direction). 

**Describe alternatives you've considered**
Doing this manually

**Comment by CommonClimate** [comment]
the "y" flip is implemented in 06974983d7f987aefb2e13c7a7e89def0f1456b6, along with log-keeping and a search for previous flips (with warning). This is illustrated in [Tracing Transformations](https://github.com/LinkedEarth/PyleoTutorials/blob/main/notebooks/L2_tracing_transformations.ipynb)

**Comment by CommonClimate** [comment]
now implemented for `MultipleSeries` as well in 9d7a1c0a40a8d045a714ac8d1d58f85d33b9e325.  Open question: should it be added to LipdSeries as well?

**Comment by CommonClimate** [comment]
I'm closing this as `convert_time_unit` enabled the time flip already

**Comment by alexkjames** [comment]
add in the ability to time flip (convert_time_unit be damned)

**Comment by alexkjames** [comment]
This is in fact a bad idea, julien was right
