### ISSUE TITLE
Incompatibility between specific cartopy and matplotlib versions

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#279]
With `py3.9`, the default `cartopy` version being installed via `conda install -c conda-forge cartopy` is `0.19.0.post1`. Since `matplotlib` is its dependency, `3.5.3` is installed, but when install Pyleoclim, matplotlib is forced to upgrade, leading to incompatibility. Manual upgrading `cartopy` to `0.21` can fix it. With `py3.10`, the default `cartopy` version being installed is `0.21`, which is compatible with the current Pyleoclim `setup.py`. 

Therefore, we need to modify the documentation as `conda install -c conda-forge cartopy=0.21` or above for users with `py3.9`.

**Comment by khider** [comment]
Fixed in [5637fc7](https://github.com/LinkedEarth/Pyleoclim_util/commit/5637fc71babe4f9c84dfb1a0094d5b340fbaffa4)
