### ISSUE TITLE
Warming stripes are not warming in the correct place

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#281]
**Describe the bug**
When running with Kaplan SST, suggests that the warmest period is 1940-1960.

**To Reproduce**
Data is from: [https://github.com/LinkedEarth/PyleoTutorials/blob/main/data/wtc_test_data_nino_even.csv](https://github.com/LinkedEarth/PyleoTutorials/blob/main/data/wtc_test_data_nino_even.csv)

import pyleoclim as pyleo
import pandas as pd

df = pd.read_csv('../data/wtc_test_data_nino_even.csv')
df.head()

ts_nino = pyleo.Series(time =  df['t'], value = df['nino'], label = 'Kaplan Niño3 SST',
                  time_name = 'Year', value_name = 'NINO3 index',
                  time_unit = 'CE',   value_unit = '$^{\circ}$C')            

fig, ax = ts_nino.plot()

fig, ax = ts_nino.stripes(ref_period=(1961,1990), show_xaxis=True)

**Expected behavior**
Appropriate warm intervals

**Screenshots**

<img width="965" alt="image" src="https://user-images.githubusercontent.com/11758571/207732295-1b87aeec-bf90-4762-a0f5-b4bb71c169d2.png">

<img width="902" alt="image" src="https://user-images.githubusercontent.com/11758571/207732325-1d3c0158-a08d-4bb2-8894-f5010f705e40.png">

**Comment by CommonClimate** [comment]
addressed by #398
