### ISSUE TITLE
Arrays are not enforced in series objects

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#293]
Currently series objects do not enforce the usage of numpy arrays for the time and value attributes. However, some methods, such as .slice(), require that the time and value axis are numpy arrays (in the case of slice, the function tries to apply a mask array to the time and value axis). This results in such methods not working for hard to discern reasons. In this case, a user might create a series using lists and then try to apply slice, only to get an esoteric TypeError.

To recreate this bug:

* Apply `.bin()` and then `.slice()` to any series. `.bin()` returns a series with lists for the time and value attributes.

There are two solutions available that I can think of:

* Force conversion of time and value axis into arrays when series objects are created (preferred)
* Fix .slice() specifically so that it converts the time and value attributes into arrays at the beginning of the function

**Comment by alexkjames** [comment]
Also, certain methods return series objects with the time and value attributes as lists. `.bin()` is one such method.

**Comment by CommonClimate** [comment]
@alexkjames I am confused: lines 148-149 of series.py literally do just what your first bullet proposes:

 `self.time = np.array(time)
 self.value = np.array(value)`

perhaps you mean to enforce this in the tsutils-level methods like like bin()? If so, I agree. Besides bin(), have you found this to be the case for other methods?

**Comment by CommonClimate** [comment]
For bin(), this is an easy fix:

res_dict = {
        'bins': np.array(bins),
        'binned_values': np.array(binned_values),
        'n': n,
        'error': np.array(error),
    }

**Comment by alexkjames** [comment]
Strange! I would've thought that would preclude the possibility of list objects being assigned to those attributes. Then yes, I think we should double check the utils for functions that reassign those attributes as non-array objects. I only noticed this today with `bin()`, I haven't noticed it with other methods yet.

**Comment by CommonClimate** [comment]
OK - can you please have a look-through and fix whatever needs to be fixed (starting with `bin()`) ?

**Comment by alexkjames** [comment]
Yes! I'm going to close this issue and create one thats a bit more accurate to the problem.
