### ISSUE TITLE
Certain methods replace `time` and `value` series attributes with lists

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#294]
**Describe the bug**
Certain methods replace `time` and `value` series attributes with lists, which breaks other methods such as `slice()` that rely on these attributes being arrays.

**To Reproduce**
Run `.bin()` and then `.slice()` on any series object.

**Expected behavior**
All methods that return series type objects should maintain the time and value attributes as arrays.

**Proposed fix**
Go through methods, specifically tsutils level methods, and ensure that time and value attributes are being returned as arrays.

**Comment by CommonClimate** [comment]
Addressed by #314
