### ISSUE TITLE
Unit Tests / CI?

### ISSUE THREAD

**Issue by oscarbranson** [LinkedEarth/Pyleoclim_util#30]
Is there a plan to implement unit tests or continuous integration checks (e.g. [TravisCI](https://travis-ci.org/))? This will *definitely* ease development as the project grows.

I may be able to help with this if wanted.

**Comment by CommonClimate** [comment]
Hi @oscarbranson, thanks for your interest.  Yes, we have been thinking of moving that way but lack the experience. If you wanted to offer some help, we'll gladly take it. 

What unit test(s) would you see as a priority?

**Comment by oscarbranson** [comment]
To be useful, the tests should check that all functions in the package work, and that the output of data analysis using those functions is conserved across versions. In an ideal world, this would mean a unit test for each individual function, in addition to a test that runs an entire analysis script and checks the output against some 'correct' reference values. When you've already got quite a bit of code written, implementing the former is a massive headache (from experience!). However, you can get a lot of utility with just that latter, which implicitly tests all underlying functions behind the analysis. If the test errors out you normally get an informative enough message to work out what you've broken without too much grief. A good starting point might be to just implement the scripts in the 'examples' folder as tests, which can be run as a consistency check before pushing updates.

You can see an example of this type of retro-fitted testing in [one of my repositories](https://github.com/oscarbranson/latools/tests).

As an added bonus, you can then set this up on a service like Travis CI which runs the test suite on checks all commits and pull requests automatically.

If that sounds useful, I can have a go at implementing this over the next couple of weeks.

**Comment by CommonClimate** [comment]
Hi Oscar, I talked to the main developers (@khider and @fzhu2e), and we like the idea of you trying to build automated tests using the Example notebooks already in place. We *think* they call all the functions in the package, but it might not hurt to check.  Just do a traditional pull request when you're happy with it, and we can merge then. We much appreciate your involvement, and are excited to see Pyleoclim used outside our research group!

**Comment by oscarbranson** [comment]
Had a brief look at this yesterday to assess feasibility, but ran into a daft problem: my computer is too full to install the large number of packages required by pyleoclim!

Also, from looking at the examples in more detail, is not exactly clear to me what the 'targets' of testing might be.

Will try to take a look at this next month when I have a new computer.

**Comment by khider** [comment]
Tests are performed for the functions in ui.py, which calls for base functions in utils.
