### ISSUE TITLE
Switch version to be PEP 440 compliant

### ISSUE THREAD

**Issue by kcpevey** [LinkedEarth/Pyleoclim_util#315]
**Describe the bug**

With versions of `setuptools` >= 66, `pip install -e .` fails because the version number `1.0.0b` is invalid. 

**Expected behavior**
I expect it to install in dev mode without error

**Additional context**

The short story is that 1.0.0b is an invalid version according to PEP 440
```
In [2]: from pep440 import is_canonical
In [3]: is_canonical("1.0.0b")
Out[3]: False
```

We have two solutions here.
Pin `setuptools` to <66 because 65.x hadn’t deprecated LegacyVersion yet.
Change the version to `1.0.0b0` which is compliant.

In some versions of `setuptools`, it attempts to make it compliant during the install. Some will succeed by turning it into `1.0.0b0` while other versions somehow end up with `1.0.0ba` which fails.

**Comment by CommonClimate** [comment]
Thanks for creating the issue. Do you mean setuptools >=66 ? It sounds like <66 would include 65.x, which is part of the problem.  
By the way, this dev install is resolved, seemingly, in my old environment with just updating pandas to the nightly wheel. Not sure why.

**Comment by kcpevey** [comment]
I meant pin to `<66` as stated. `65.x` still includes the functionality that allows for the format of `1.0.0b` to pass (`LegacyVersion`). `66` deprecates it and enforces PEP 440 formats which fails with the current version format.

**Comment by CommonClimate** [comment]
OK. Do you want to do  PR about this?

**Comment by kcpevey** [comment]
yep, I can do that!

**Comment by kcpevey** [comment]
Version syntax is now compliant in `Development` branch. Closed by https://github.com/LinkedEarth/Pyleoclim_util/pull/319
