### ISSUE TITLE
Fortran compiler

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#33]
Change the import to fortran code to be within the function so the package doesn't fail on import.  Put a warning that the method is slow and we strongly suggest installing said compiler.

**Comment by fzhu2e** [comment]
For windows:  `conda install -c msys2 m2w64-gcc-libgfortran `

**Comment by fzhu2e** [comment]
With [the recent commit](https://github.com/LinkedEarth/Pyleoclim_util/commit/6621114a2ef92e39117555cbc6e135b379cdbd0c), the importing lines for f2py has been moved inside the function that calls `f2py`, so the Fortran code is not required to be compiled and will not be compiled automatically (same case for `rpy2`). So now the installation steps are very simple now:
```python
conda create -n pyleoclim python=3.7
conda install -n pyleoclim -c conda-forge cartopy
conda activate pyleoclim
pip install pyleoclim  # with my modified setup.py
```

We should provide instructions of compiling the Fortran code  and installing `rpy2` in the documentation later.

**Comment by CommonClimate** [comment]
That sounds great. I hope it works on Windows machines too...

**Comment by khider** [comment]
Now using numba
