### ISSUE TITLE
Knee finding method for identifying significant ssa eigenvalues

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#331]
**Is your feature request related to a problem? Please describe.**
The current ssa truncation choices for selecting "significant" can occasionally be wanting. Using a knee finding algorithm to identify the cutoff point for eigenvalues has shown some promise as being a convenient and robust statistic.

**Describe the solution you'd like**
Implement knee finding technique for ssa truncation

**Comment by alexkjames** [comment]
This repository for knee finding: https://pypi.org/project/kneed/

**Comment by CommonClimate** [comment]
I'd mention that you have already implemented it externally, with satisfactory results

**Comment by alexkjames** [comment]
Closed with #345
