### ISSUE TITLE
pandas-enabled updates to MultipleSeries

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#359]
**Is your feature request related to a problem? Please describe.**
pandas integration has enabled several enhancements to Series, which need to be generalized to MultipleSeries:
- [x] to_csv()
- [x] to_json()
- [x] __disp__
- [x] view()
- [x] sel()

@khider can you take care of the JSON one?

**Comment by CommonClimate** [comment]
to_csv enabled in #373

**Comment by CommonClimate** [comment]
disp and view implemented in 84463a5821d486056da29d8bec3545df8f4d63bc. Examples of use in the [paleopandas playground](https://github.com/LinkedEarth/paleoPandas/blob/main/notebooks/Paleopandas%20Playground.ipynb)

**Comment by khider** [comment]
`.sel` is enabled in 037eb592a5ec49b7f1be1af458a60352846a93ef.

**Comment by khider** [comment]
`to_csv` needs to be slightly change to be consistent with how Pyleoclim (and Pandas) handle files and path. Just use path=None for a default path + filename.

**Comment by khider** [comment]
Export to/import from JSON available in: ab52606
