### ISSUE TITLE
Clean up time: data folder

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#378]
Our data folder has become a jumble mess since it was used for multiple purposes. It should only contain datasets needed for tests and doc building.

**Comment by CommonClimate** [comment]
One downside of removing the dev branch: statements like 
```
pd.read_csv(
   ...:     'https://raw.githubusercontent.com/LinkedEarth/Pyleoclim_util/Development/example_data/soi_data.csv',
   ...:     skiprows=0, header=1
   ...: )
```
   
now fail in the docs. I'll get started on purging them.

**Comment by CommonClimate** [comment]
Purge list:

- [  ] coherence.py
- [  ] corr.py
- [  ] correns.py
- [  ] ensembleseries.py
- [  ] lipd.py
- [  ] lipdseries.py
- [  ] multipleseries.py
- [  ] psds.py
- [  ] scalograms.py
- [  ] series.py
- [  ] spatialdecomp.py
- [  ] ssares.py
- [  ] surrogateseries.py

**Comment by CommonClimate** [comment]
I am leaving lipd.py and lipseries.py for the pyLipd days.

**Comment by alexkjames** [comment]
labelled datasets: https://docs.google.com/spreadsheets/d/1eiBtMuPUzJbiuMbxjT5cG5kILpgNW-sQpBQ9L1bLGKM/edit#gid=0
