### ISSUE TITLE
Issue with gkernel method

### ISSUE THREAD

**Issue by rhysea** [LinkedEarth/Pyleoclim_util#380]
I was trying to coarse-grain a series using the following code:

tc, yc = pyleo.utils.gkernel(pdsi_df['time'],pdsi_df['pdsi'],time_axis=psAD.time)

I ran into this error:

`---------------------------------------------------------------------------`
UnboundLocalError                         Traceback (most recent call last)
Cell In[24], line 16
      6 ps = pyleo.Series(
      7     id_df["time"],
      8     id_df["charcoal_measurement"],
   (...)
     13     value_unit="$\mathregular{cm^{3}}$",
     14 )
     15 psAD = ps.convert_time_unit('years AD')
---> 16 tc, yc = pyleo.utils.gkernel(pdsi_df['time'],pdsi_df['pdsi'],time_axis=psAD.time)

File ~/opt/anaconda3/envs/thesis_pyleo/lib/python3.10/site-packages/pyleoclim/utils/tsutils.py:481, in gkernel(t, y, h, step, start, stop, step_style, evenly_spaced, bin_edges, time_axis, no_nans)
    478     else:
    479         yc[i] = np.nan
--> 481     yc /= sum(weight) # normalize by the sum of weights
    482 return time_axis, yc

UnboundLocalError: local variable 'weight' referenced before assignment`

---------------------------------------------------------------------------

Would be great to have a fix soon!

**Comment by CommonClimate** [comment]
Hi Shreya, i believe the issue has been fixed in PR #381. Can you re-install the package and try your notebook again?

**Comment by rhysea** [comment]
Reinstalled but still having the same error.

**Comment by CommonClimate** [comment]
That is strange. Did you restart the notebook?

**Comment by alexkjames** [comment]
Closed with #381
