### ISSUE TITLE
Documentation glitches

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#389]
**Describe the bug**
Lots of figures don't appear correctly.
Most compound figures need `fig.tight_layout()` so the edges appear correctly. 
 In addition, we need to fix:
- [x] MultipleSeries docstring needs to mention `label`, not `name`
- [x] series.detrend() : no figures at all
- [x] series.filter() (legend needs a semi-transparent box as it's not visible otherwise)
- [x] series.spectral() : psd_mtm2 doesn't render
- [x] series.ssa(): RCk length mismatch
- [x] series.stripes(): plots don't render
- [x] series.summary_plot(): fonts are too large and labels conflict with each other
- [x] series.summary_plot(): bug in the parameter section
- [x] series.wavelet() : "have different amplitude" --> "have different amplitudeS"
- [x] multipleseries.append(): adding SOI to SOI triggers error message. Use NINO3 instead. 
- [x] multipleseries.common_time(): no figures at all
- [x] multipleseries.flip(): stackplot() labels not visible (tight_layout issue?)
- [x] multipleseries.stackplot(): labels not visible (tight_layout issue?)
- [x] ensembleseries.correlation(): series creation needs `verbose=False` to prevent vomiting identical messages; 
- [x] corr_res.plot() figure far too wide and truncated  (tight_layout issue?). 
- [x] ensembleseries.histplot(): series creation needs `verbose=False` to prevent vomiting identical messages
- [x] ensembleseries.plot_envelope():  series creation needs `verbose=False` to prevent vomiting identical messages
- [x] ensembleseries.plot_traces():  series creation needs `verbose=False` to prevent vomiting identical messages
- [x] ensembleseries.quantiles():  series creation needs `verbose=False` to prevent vomiting identical messages
- [x] ensembleseries.slice(): sorting messages need to be silenced (probably needs to happen within `series.copy()`). 
- [x] ensembleseries.stackplot():  series creation needs `verbose=False` to prevent vomiting identical messages
- [x] multiplepsd.plot_envelope():  series creation needs `verbose=False` to prevent vomiting identical messages
- [x] remove references to LiPD files outside of LiPD or LIPDSeries classes ; otherwise ignore.
- [x] pyleoclim.utils.correlation.cov_shrink_rblw() Very little of the math seems formatted properly
- [x] pyleoclim.utils.wavelet.AliasFilter() some wonkiness going on here, not sure how to describe
- [x] pyleoclim.utils.tsutils.gkernel() is broken, bad code
- [x] pyleo.utils.tsutils.interp() is broken, bad code

**Comment by CommonClimate** [comment]
#390 addresses the ensemble series `plot_envelope()` problem

**Comment by khider** [comment]
Sorry to re-open this, but we should probably change the front page saying that Pyleoclim natively speaks LiPD. Won't be true very soon and we do need to start moving people away from these two classes.

> Pyleoclim natively “speaks” the language of Linked Paleo Data ([LiPD](http://lipd.net/)), which enables it to handle most of the data transformations internally, taking a good chunk of the pain out of analyzing paleoclimate data. The package is aware of age ensembles stored via LiPD and uses them for time-uncertain analysis. Age ensembles can be generated through the [GeoChronR](http://nickmckay.github.io/GeoChronR/) package, which natively stores them as ensemble tables in LiPD.
> 
> While convenient for the representation of paleoclimate observations, LiPD is not the only point of entry into Pyleoclim. The [Series](https://pyleoclim-util.readthedocs.io/en/latest/core/api.html#core-api) class is very flexible, and allows to apply Pyleoclim functionality to virtually any timeseries, including instrumental or model-generated data, as Excel spreadsheets, numpy arrays or pandas dataframes. Indeed, Pyleoclim is the workhorse supporting more general [machine-learning functionalities](https://github.com/KnowledgeCaptureAndDiscovery/autoTS) for all manner of timeseries.

**Comment by CommonClimate** [comment]
What phrasing would gain your approval?

**Comment by khider** [comment]
That the Series and GeoSeries class are very flexible and allows to apply Pyleoclim functionality to virtually any timeseries, including instrumental or model-generated data, as Excel spreadsheets, numpy arrays or pandas dataframes. It is also capable of working with datasets stored in the LiPD format, through the PyLiPD package.
