### ISSUE TITLE
Standardization

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#4]
We need a function like this one http://www.clidyn.ethz.ch/imputation/standardize.m 

Notice that it returns 3 things: the z-score, the original mean and original standard deviation.

Among other things, it can be used to scale a record to a match a given variance.

**Comment by fzhu2e** [comment]
The `standardize()` function has been added into [Timeseries.py](https://github.com/LinkedEarth/Pyleoclim_util/blob/master/pyleoclim/Timeseries.py).
