### ISSUE TITLE
Odd gkernel behavior for certain series

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#402]
Currently certain time series (GISP2 for example) cause gkernel to fail when passed with default arguments. This seems to be due to an issue with the e-folding scale parameter resulting in very small weights for certain time axes, which python interprets as being zero, resulting in a division by zero error when we try to normalize the values. This is mainly a problem when the distance between time points >> h. 

We may need to do some automatic adjustment of the e-folding scale (`h` argument) in order to avoid this issue. 

To recreate:

ts = pyleo.utils.load_dataset('GISP2')
ts.gkernel()

**Comment by CommonClimate** [comment]
I recommend asking [Kira Rehfeld](https://www.iup.uni-heidelberg.de/en/institut/mitarbeiter/dr-kira-rehfeld) for advice on an automated search criterion, as our function is based on some of her PhD work, and I bet some further work has been done on this topic since then.

**Comment by khider** [comment]
Also, we may want to have a CI test enabled that take the problematic series in as well so we know if we're fixing the problem.

**Comment by CommonClimate** [comment]
Agreed. Especially a series that's part of the package!

**Comment by alexkjames** [comment]
Change default value for `e` to None and set to median time step with check for nans. If nans are still present use max time step

**Comment by alexkjames** [comment]
Fixed in #465
