### ISSUE TITLE
mapping a GeoSeries' neighbors

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#430]
**Is your feature request related to a problem? Please describe.**
The LipdSeries class has a function called `mapNearRecord()` which plots nearby records. The `GeoSeries` class needs an equivalent. 

**Describe the solution you'd like**
A method attached to GeoSeries (e.g. `gs`), which takes as mandatory argument a MultipleGeoSeries object (e.g. `mgs`), with this syntax  `gs.map_neighbors(mgs, radius = 3000, projection='Orthographic', .... )`.  By default, LipdSeries plots a set number of records, which I would prefer to abolish; the more relevant behavior is to plot all records within a certain radius (e.g. 3000 km by default, to ensure that most databases will have at least one record in that neighborhood). Note that `mapping.py` already contains utilities like `compute_dist` to compute great circle distances and return a list of records within a prescribed radius, so no need to re-invent the wheel. By default, the maps should show archiveType as the main semantic (with default colors/shapes) but once @jordanplanders 's seaborn-based mapping improvements are in, we can throw in some size semantics as well (by default, for elevation/depth). 

**Describe alternatives you've considered**
doing this outside Pyleoclim, which would be a pity.

**Comment by khider** [comment]
I did a set number of records back then with the hope that we could spit them out back to users if they just want to look at the closest ones for a stack plot. Was never implemented.

**Comment by CommonClimate** [comment]
I see. We could think of exporting something more than just `fig, ax`, but I am loathe to break precedent here. Maybe we can just show in a tutorial how to leverage `compute_dist` and `within_distance` to do this outside the mapping function?

**Comment by CommonClimate** [comment]
Addressed by #441
