### ISSUE TITLE
Pyleoclim is not able to handle "BP" as units of time.

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#443]
**Describe the bug**
If using BP, for functions that need to align the axis (e.g., stack plot). Pyleoclim returns an error. 

**Expected behavior**
Add BP to the list for conversion purposes. 
Also tried to set the multipleseries time unit to 'yr BP' but then it would guess incorrectly

**Comment by CommonClimate** [comment]
addressed by #445
