### ISSUE TITLE
Issues with x-axis label in pyleoclim.core.multivardecomp.modeplot()

### ISSUE THREAD

**Issue by MiaEl-Khazen** [LinkedEarth/Pyleoclim_util#447]
I imported  my data from a csv into a pd.Dataframe where my time column is df['Age_ka'] which I used to create multiple Geoseries where my time_value is the column df['Age_ka']. I call my time_name= 'Age' and my time_unit='ky BP'. when I run a pca  and plot it using pca.modeplot() my x-axis is labeled in units of [years CE]

Before I run my pca I put my multiple geoseries on a common time and standardize it: MultiGeoSeries.common_time().standardize()

**Comment by CommonClimate** [comment]
Hi @MiaEl-Khazen , it looks like you did everything right, so I'm going to need your csv file and code to debug this properly. Can you share it by private message through the LinkedEarth Community Slack? Thanks, Julien

**Comment by CommonClimate** [comment]
solved by #449
