### ISSUE TITLE
Create a resolution function for MultipleSeries object

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#448]
Right now, needs to iterate through the `series_list` to do so. 

In terms of functionality, we should allow for the ability to make plots/calculation for the individual series in the `MultipleSeries` object as well as doing summaries (i.e., one histogram plot for all series).

**Comment by CommonClimate** [comment]
I agree that such a method would be useful for `MultipleSeries`, however I am not sure I see the point of having one histogram plot for all series. Indeed, when treating `MultipleSeries` it is often essential to separate Series according to their resolution (e.g. [this notebook](http://linked.earth/PyleoTutorials/notebooks/L2_principal_component_analysis.html)). How would one do that if all the resolution values are lumped together?

However, I could imagine some kind of [boxplot](https://seaborn.pydata.org/examples/horizontal_boxplot.html) or [ridgeplot](https://seaborn.pydata.org/examples/kde_ridgeplot.html), with Series labels, being helpful for up to 10-15 series. For larger collections, it may be necessary to have colored [rugplots](https://seaborn.pydata.org/generated/seaborn.rugplot.html?highlight=rugplot) to separate the various datasets.

**Comment by CommonClimate** [comment]
@khider what's your feeling on this?

**Comment by khider** [comment]
This request was coming from a particular use case in the hackathon. In this case, the idea was to look in aggregates to make better decision on steps for `common_time`.  

I think a violin plot of all series could be useful as well.

**Comment by CommonClimate** [comment]
Recommendation from the 02/09 High Council:  boxplot + swarmplot as in https://seaborn.pydata.org/examples/horizontal_boxplot.html. Label each one with the Series label

**Comment by alexkjames** [comment]
closed with #527
