### ISSUE TITLE
Units in datasets are different for PC

### ISSUE THREAD

**Issue by ginnybarnes3** [LinkedEarth/Pyleoclim_util#473]
**Describe the bug**
units in lr04 appear as this 'â€°'
in 64-bit operating system, x64-based processor Windows

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CommonClimate** [comment]
Hi Ginny, can you try replacing the `value_unit` field of the Series object by '\u2030' and see if the problem persists? I would try it, but I don't have a PC...

**Comment by CommonClimate** [comment]
addressed by #487

**Comment by CommonClimate** [comment]
Tested successfully by @georgyfalster
