### ISSUE TITLE
Add rank-based statistics to Series.correlation()

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#475]
Currently, `Series.correlation()` only supports Pearson's product-moment correlation as metric of similarity. This is the only possible statistic for the 'ttest' option. However, the two Monte Carlo tests (isospectral and isopersistent) can use any statistic, particularly [Spearman's rho](https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient) and [Kendall's tau](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), which are rank-based and therefore more resistant to outliers.

The idea is to use the same AR(1) or phase-scrambled surrogates (see #228) to general the null distribution. For a student project, it may be useful to validate those against the [asymptotic distribution](https://www.tandfonline.com/doi/full/10.1080/02664763.2022.2137115) of those statistics.

**Comment by CommonClimate** [comment]
Update: it would make sense to enable any of the [correlation methods supported by scipy](https://docs.scipy.org/doc/scipy/reference/stats.html#association-correlation-tests), using the same nomenclature. Example:
`corr = ts1.correlation(ts2, statistic = "kendalltau")` or `corr = ts1.correlation(ts2, statistic = "spearmanr")`.
Default statistic should be `'pearsonr'`.  The function will need a check that the supplied string matches the list of allowable methods under scipy.stats.

**Comment by khider** [comment]
Depends on solving issue #228
