### ISSUE TITLE
Updating installation instructions

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#476]
As of Cartopy v0.22+, pip is the preferred install method. This would enable Pyleoclim to be installed this way as well. 

To do:
- add cartopy to setup.py
- troubleshoot
- update the documentation page
- update contribution guide for local install

**Comment by CommonClimate** [comment]
Should be resolved by #481

**Comment by khider** [comment]
Fixed in https://github.com/LinkedEarth/Pyleoclim_util/commit/c19179918b34c562933b66d92b102818c8b1ec3a
