### ISSUE TITLE
np.int depreciated

### ISSUE THREAD

**Issue by philkongo** [LinkedEarth/Pyleoclim_util#477]
**Describe the bug**
np.int is still used in pyleoclim; for example in the wave coherence function. prevents the wavelet coherence function from running. 

**To Reproduce**
1. run the coherence wavelet function
e.g. coh = ts_a.wavelet_coherence(ts_b, method = 'wwz')

**Expected behavior**
wavelet coherence function to work

**Screenshots**
![Screenshot 2023-11-23 at 12 05 38 AM](https://github.com/LinkedEarth/Pyleoclim_util/assets/53326433/d30d2bde-59ce-4e71-b9ef-3e140a8be9fe)

**Desktop (please complete the following information):**
 - OS: macos
 - Python 3.11

**Additional context**

**Comment by khider** [comment]
Which version of numpy do you have currently installed?

**Comment by CommonClimate** [comment]
Weird. My current version of the code (prior to seeing this issue) in branch `pip_install` has:
`return {'n': int(2 ** np.ceil(np.log2(len(signal))))}`  for that line. I wonder when it got changed, but it should work with this version of NumPy.

**Comment by philkongo** [comment]
I uninstalled pyleoclim and reinstalled it-- it installed numpy 1.23.5 and
now it runs!

Appreciate you both looking into it.
Phil
