### ISSUE TITLE
When using wwz for coherence the timeseries are not placed on the common axis properly

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#479]
When using wwz at the method for coherence, the timeseries are not truncated properly. According to the doc, it should use the default for `common_time`, which should lead to using the max of the min time and the min of the max time. When trying to specifically pass a start and end time, `common_time` is ignored. 

![coherence_dashbaord](https://github.com/LinkedEarth/Pyleoclim_util/assets/11758571/cfc2c496-e1af-4506-a6d2-486072dc5b94)

**Comment by CommonClimate** [comment]
Can you provide more details on this? What are you passing, and what result are you getting? A MWE to reproduce the bug would be great.

**Comment by khider** [comment]
Can't share the actual data. But I passed the two timeseries using all default option first but with `method='wwz'`. 

Then I tried:

`ts1.wavelet_coherence(ts2, method='wwz', common_time_kwargs = {'start': 800, 'stop':2002})`

It doesn't truncate. I had to slice first then use the method on the sliced timeseries.

**Comment by CommonClimate** [comment]
OK, I'll try on a mockup example

**Comment by CommonClimate** [comment]
addressed by #501
