### ISSUE TITLE
Add fmin and fmax to freq_vector_log()

### ISSUE THREAD

**Issue by neillinehan** [LinkedEarth/Pyleoclim_util#486]
**Is your feature request related to a problem? Please describe.**
I would like to examine specific scale ranges with wavelet coherence, tuning the minimum and maximum frequencies can allow more fine analysis, reducing unnecessary computation, especially with the wwz method. 

**Describe the solution you'd like**
Add fmin and fmax to allowed arguments for freq_vector_log(), and the others.

**Comment by CommonClimate** [comment]
Closing this now since I have not heard word from @neillinehan . Can be re-opened if need be.
