### ISSUE TITLE
Calculate quantiles of ages in ensemble

### ISSUE THREAD

**Issue by ekthomas** [LinkedEarth/Pyleoclim_util#502]
The EnsembleSeries.quantiles function calculates quantiles of the paleoData_values. Would be great to have a function to calculate quantiles of the ages! Thank you :)

**Comment by khider** [comment]
@CommonClimate I could add a flag to the existing function to calculate either from the value or time. 

e.g., `ms.quantiles(mode='value')` to calculate on the values, or `ms.quantiles(mode='time')` for time. `value` would be the default to keep with current behavior. 

And using `value` and `time` to keep with Pyleoclim nomenclature. 

Any objections?

**Comment by CommonClimate** [comment]
Thanks @khider, I like the design. Only thing i would change is the nomenclature: "mode" means something in stats, so i would prefer the term "axis" , compliant with NumPy usage.
