### ISSUE TITLE
'matplotlib' option no longer working in utils.plotting.set_style()

### ISSUE THREAD

**Issue by evepug** [LinkedEarth/Pyleoclim_util#513]
Bug description: I prefer to avoid changes to default matplotlib formats that occur when importing pyleoclim by using the 'matplotlib' option in pyleo.utils.plotting.set_style(), but since updating to a newer version of the package in the past week, this option no longer seems available (although it is still listed in the documentation). 

To reproduce:
from pyleoclim import utils
utils.plotting.set_style(style='matplotlib')

Which returns the error message: 
ValueError: Style [matplotlib] not availabel!

Choosing other style options like 'journal' or 'web' runs without errors and seems to work as expected. 

Looking at the source code for the utils.plotting.set_style function, it appears that the 'matplotlib' style option is not defined anywhere, whereas the other options (journal, web, spines, etc.) are defined. Restoring this option so it's possible to import pyleoclim and keep current matplotlib settings without having to reset rcparams would be helpful. 

Edit to add: I'm using version 0.13.0

**Comment by khider** [comment]
Do you remember when you last used this option? Trying to roll back but it would help to have a date

**Comment by khider** [comment]
@fzhu2e Seems that it was removed in commit [8fffc09](https://github.com/LinkedEarth/Pyleoclim_util/commit/8fffc098d826d42267c5fdeb113799b1fb5c7f19). Any ideas why?

**Comment by evepug** [comment]
@khider Looks like you already found where it was removed, but in case it's still useful I was previously using a version of the package I think I downloaded in early 2021.

**Comment by fzhu2e** [comment]
> @fzhu2e Seems that it was removed in commit [8fffc09](https://github.com/LinkedEarth/Pyleoclim_util/commit/8fffc098d826d42267c5fdeb113799b1fb5c7f19). Any ideas why?

Sorry, it has been too long and I can't remember exactly why I removed that. It's probably that it's not working as expected in certain cases at that time, and I did that to avoid confusion. Please feel free to put it back and have a test to see if it works. Things could be different now.

**Comment by khider** [comment]
Ok, I reinstated matplotlib on my version of the code. Two concerns:
1. By default, Matplotlib doesn't show plots anymore. So one needs to do the following:
```
import pyleoclim as pyleo
import matplotlib.pyplot as plt
pyleo.set_style('matplotlib')

ts = pyleo.utils.load_dataset('LR04')
fig,ax=ts.plot()
plt.show(fig)

```

Second concern: The stack plot doesn't work with this style:

![image](https://github.com/LinkedEarth/Pyleoclim_util/assets/11758571/c583ed0d-5ead-45c0-a4c2-18e444eb1dda)

I could put a warning when the style is selected that some functionalities may no longer work and push the change. Any suggestions @CommonClimate  and @fzhu2e ?

**Comment by evepug** [comment]
Sorry to intrude but would it be possible to just leave the rc params as
they are by passing a blank style_dict instead of restoring to default
rcparams? I did a quick test and it looks like
mpl.rcParams.update(plt.rcParamsDefault) is what messes up the automatic
display of plots. But I guess this would not fix the problem with stackplot
probably.

See my minimum reproducible example below, which does not not mess up
automatic display of plots:

import matplotlib as mpl
import matplotlib.pyplot as plt

def set_style(style='matplotlib',font_scale=1,dpi=400):

    font_dict = {
                'font.size': 10,
                'axes.labelsize': 11,
                'axes.titlesize': 12,
                'xtick.labelsize': 10,
                'ytick.labelsize': 10,
                'legend.fontsize': 9,
                }

    style_dict = {}

    if 'matplotlib' in style:
        style_dict.update({
        })

    figure_dict = {
                  'savefig.dpi': dpi,
                  }

    font_dict.update({k: v * font_scale for k, v in font_dict.items()})

    for d in [style_dict, font_dict, figure_dict]:
        mpl.rcParams.update(d)

set_style()

data=range(0,100,10)
plt.plot(data,data)
_________________________________________________________________________
If I replace the following:

if 'matplotlib' in style:
        style_dict.update({
        })

with the original version:

if 'matplotlib' in style:
        mpl.rcParams.update(plt.rcParamsDefault)

this leads to the problem with the plot not displaying without calling
plt.show().

Best,
Eve

**Comment by evepug** [comment]
thank you!

**Comment by fzhu2e** [comment]
> Ok, I reinstated matplotlib on my version of the code. Two concerns:
> 
>     1. By default, Matplotlib doesn't show plots anymore. So one needs to do the following:
> 
> 
> ```
> import pyleoclim as pyleo
> import matplotlib.pyplot as plt
> pyleo.set_style('matplotlib')
> 
> ts = pyleo.utils.load_dataset('LR04')
> fig,ax=ts.plot()
> plt.show(fig)
> ```
> 
> Second concern: The stack plot doesn't work with this style:
> 
> ![image](https://private-user-images.githubusercontent.com/11758571/304877550-c583ed0d-5ead-45c0-a4c2-18e444eb1dda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5Njg4MzIsIm5iZiI6MTcwNzk2ODUzMiwicGF0aCI6Ii8xMTc1ODU3MS8zMDQ4Nzc1NTAtYzU4M2VkMGQtNWVhZC00NWMwLWE0YzItMThlNDQ0ZWIxZGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDAzNDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZDA1Y2Y1ZGI5MGQ3YzA5YmY0NGJlODYxMjNmMTY2MjAyZjJmOGJiYzVmMWUxNzU4ZTA5OWFhOWUzNTQwYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wng98BiBMBLQXbGIPUSVkqzcgB-RClregf1e58qAC40)
> 
> I could put a warning when the style is selected that some functionalities may no longer work and push the change. Any suggestions @CommonClimate and @fzhu2e ?

Yes, I agree a warning is needed. stackplot is a unique application and the style is hard-coded.
