### ISSUE TITLE
MultivarDecomp.modeplot() arguments - new default + fix when archiveType is not provided

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#514]
When the archiveType is not provided in the GeoSeries, the map doesn't make much sense using the defaults:

_Problem 1:_

![image](https://github.com/LinkedEarth/Pyleoclim_util/assets/11758571/82fb7542-96e6-451c-ab96-441b75d9bae8)

The work around is to set `marker='o'` but I would expect that by default, I get something better than question marks when archiveType (default for marker setting) is None. I would write a condition that if archiveType is None for all GeoSeries in the MultipleGeoSeries object, then set marker to 'o'.

_Problem 2:_

The legend on the right doesn't make sense when there are no archiveType provided. But when using the command: `scatter_kwargs={'legend':False}`, the colorbar disappears.

![image](https://github.com/LinkedEarth/Pyleoclim_util/assets/11758571/82727e29-5912-4024-86d8-d1006cb925a1)

**Comment by CommonClimate** [comment]
Solution agreed upon by the High Council on 02/09/2024: 
- [ ] make `marker=None` the default for MultivarDecomp.modeplot()
- [ ] update docstring to mention the possibility of `archiveType`
- [ ] update the docstring example of MultipleGeoSeries.pca() to specify `marker = 'archiveType'`

**Comment by khider** [comment]
Fixed with #525
