### ISSUE TITLE
Corrsig: handle ensembles 

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#53]

**Comment by fzhu2e** [comment]
A version is implemented in the commit d4640d9c16352cd5fe3030c4dbc693027e9ffa5e.

**Comment by khider** [comment]
Add notebook and example in docstring.
Note that this function assumes that the series have a common axis and the same binning/interpolation interval (i.e. a common time axis)

**Comment by fzhu2e** [comment]
Added the docstrings example in commit 27a82ea.

**Comment by khider** [comment]
Case scenario:

- 1 series another series within the same object -> common_time (check that all the series are under the same common axis). Put under MultipleSeries (TODO)

- 1 series vs an ensemble series -> correlate the series vs each member of the ensemble (current implementation)
- Ensemble Series vs Ensemble Series (should be under EnsembleSeries) -> randomly select 100s of members in each and correlate. (current implementation)

**Comment by fzhu2e** [comment]
Here is the notebook to demonstrate the correlation computation in Pyleoclim: https://gist.github.com/fzhu2e/78f8cff53d285ae215bec2ef87f0df14   It’s based on a version of ui.py that is not pushed yet, but can be accessed in the bottom of the webpage. For MultipleSeries.correlation() see https://gist.github.com/fzhu2e/78f8cff53d285ae215bec2ef87f0df14#file-ui-py-L2756-L2839 For EnsembleSeries.correlation() see https://gist.github.com/fzhu2e/78f8cff53d285ae215bec2ef87f0df14#file-ui-py-L3127-L3246
