### ISSUE TITLE
binTs, interpTs for ensembles 

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#54]
Mean spacing: mean of the median for a realization
start_time: max(min)
end_time: min(max)

**Comment by CommonClimate** [comment]
note: use SOI and All India Rainfall to create a 2-MultipleSeries object.

**Comment by CommonClimate** [comment]
if ms is a MutipleSeries object, define `ms.bin()` as `ms.common_time(method='bin')` and  `ms.interp()` as `ms.common_time(method='interp')` (with all the same defaults and parameters)

**Comment by khider** [comment]
Needs example in docstrings.

**Comment by khider** [comment]
Incorporate extrap error in the kwargs arg doc of the the interp function
