### ISSUE TITLE
Surrogate_series.from_params() breaks when using time_pattern='specified'

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#544]
**Describe the bug**
When I try to use a specified `time_pattern` with `pyleo.Surrogate_series.from_params`, I get a `AssertionError: The size of time axis and data value should be equal!`

Note this is only the case when `number=1`.

**To Reproduce**
surr = pyleo.SurrogateSeries(method='uar1',number=1)
time = np.arange(50)
surr.from_param(param=[1,1],time_pattern='specified',settings={'time':time})

**Comment by alexkjames** [comment]
@CommonClimate New erros popped up in #545 that I didn't catch right away:

Try:

ar_surr = pyleo.SurrogateSeries(method='uar1',number=1)
ar_surr.from_params(time_pattern='even',param=[1,1,])

and:

cn_surr = pyleo.SurrogateSeries(method='CN',number=1)
cn_surr.from_params(time_pattern='specified',param=[1],settings={'time':np.arange(50))

**Comment by CommonClimate** [comment]
addressed by [6e518cc](https://github.com/LinkedEarth/Pyleoclim_util/commit/6e518ccd836f4e4eecabe0df3bbda577f1b59bb7)
