### ISSUE TITLE
Cross-spectral function

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/Pyleoclim_util#556]
**Is your feature request related to a problem? Please describe.**
Create a cross-spectral coherence method.

**Describe the solution you'd like**
Probably best to use the output of wavelet coherence and integrate time to get a global mean for coherence at different periodicities.

**Describe alternatives you've considered**
There are other approaches we could try, but there's no real industry standard.

**Comment by CommonClimate** [comment]
addressed by #573 ?

**Comment by alexkjames** [comment]
Closed with #573
