### ISSUE TITLE
Add api.py  for upper function (not LiPD  workflow)

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#60]
@fzhu2e and @CommonClimate Feng proposed to do this for the functions that are workflows but don't use a LiPD file for the data.

I  agree with him that it will make things cleaner for a user, who won't have to mess with modules if they don't want LiPD. 

My only suggestion would be to not name this api.py

**Comment by khider** [comment]
See example notebook here: https://github.com/LinkedEarth/Pyleoclim_util/blob/Development/example_notebooks/api_examples.ipynb

**Comment by khider** [comment]
api.py would support upper workflows either using a  LiPD file or timeseries defined through another mean.
@fzhu2e : design classes for all the workflows
@khider : integrate LiPD support

**Comment by khider** [comment]
See this issue for Spectral:[issues46]( https://github.com/LinkedEarth/Pyleoclim_util/issues/46)

**Comment by khider** [comment]
Functions in plot.py should be under class methods

**Comment by CommonClimate** [comment]
This all makes sense, but i am not sure why it should not be called "api.py". If it is not advisable, please suggest an alternative.

**Comment by khider** [comment]
Because you insisted that the package should be imported as "import pyleoclim as pyleo", if we allow for the full name then it will be "import pyleoclim.api as pyleo" 

We can call is "api.py" internally and do an import within init to get to the first style.
