### ISSUE TITLE
ModuleNotFoundError: No module named 'pyleoclim.core.ui' 

### ISSUE THREAD

**Issue by gogogo617** [LinkedEarth/Pyleoclim_util#610]
**Describe the bug**
Hello, I tried to install this package in my environment, but I encountered a problem: Traceback (most recent call last):
  File "E:LMRtdd.py", line 1, in <module>
    import LMRt
  File "E:LMRtLMRt__init__.py", line 5, in <module>
    from .reconjob import ReconJob
  File "E:LMRtLMRtreconjob.py", line 13, in <module>
    from .proxy import ProxyDatabase
  File "E:LMRtLMRtproxy.py", line 13, in <module>
    from pyleoclim.core.ui import (
ModuleNotFoundError: No module named 'pyleoclim.core.ui'
I looked for modules in Core and didn't find a UI module.

**Comment by khider** [comment]
The newest version of Pyleoclim no longer uses this nomenclature. Was it installed as part of another package?

**Comment by CommonClimate** [comment]
it looks like it was installed as part of LMRt, now deprecated. Better to use cfr: https://fzhu2e.github.io/cfr/

Julien Emile-Geay,  professor
University of Southern California


On Jul 29, 2024, at 18:06, Deborah Khider ***@***.***> wrote:

﻿

The newest version of Pyleoclim no longer uses this nomenclature. Was it installed as part of another package?
