### ISSUE TITLE
How to improve resolution of WTC?

### ISSUE THREAD

**Issue by thelightonmyway** [LinkedEarth/Pyleoclim_util#623]
I'm learning the method on `wavelet_coherence` in `pyleoclim` and I find it very convenient!

However, I'm facing some difficult that I found my plot is a little difference when I reproduce others work. I guess it's due to the resolution. How can I change some parameters to improve the resolution? For example, specify that mother wavelet as morlet wavelet, 2 months as the starting scale, 12 sub-octaves per octave and 84 as the total number of scales. 

The left is my reproduction and the right is the result from the paper [https://doi.org/10.1029/2023GL103323](url)

![image](https://github.com/user-attachments/assets/f39f6276-f026-4920-a383-385f4ae410bd)

By the way, the data series pre-processed could be download.
[MonthlyAnomSWS_IP.txt](https://github.com/user-attachments/files/17686183/MonthlyAnomSWS_IP.txt)
(The data from the paper [https://doi.org/10.1029/2023GL103323](url))
and 
[pv.txt](https://github.com/user-attachments/files/17686191/pv.txt)

Thanks, sincerely!

**Comment by CommonClimate** [comment]
Hello @thelightonmyway and glad you are finding the package useful!

Given that the paper you mention seems to use Aslak Grinstead's code, which was based on Torrence & Compo 1998, I believe you can achieve the results you want by playing with  the frequency vector. 

You can use [this function](https://pyleoclim-util.readthedocs.io/en/latest/utils/introduction.html#pyleoclim.utils.wavelet.freq_vector_scale) to generate a frequency (scale) vector with the resolution you want and then pass it to `Series.wavelet_coherence()` as the `freq` argument. We show something similar in [this tutorial](http://linked.earth/PyleoTutorials/notebooks/L2_wavelet_analysis.html#customizing-the-frequency-range) though this is not exactly what you want. All you need to do to access the function I mentioned is 
`from pyleoclim.utils.wavelet import freq_vector_scale`

then you'll be on your way. Please let us know what you get!

**Comment by CommonClimate** [comment]
PS: I am closing this issue as solved. In the future, questions of this kind are best asked in the [discussion forum](https://github.com/LinkedEarth/Pyleoclim_util/discussions), as this is not an "issue" with the code, only a matter of usage.

**Comment by thelightonmyway** [comment]
> Hello @thelightonmyway and glad you are finding the package useful!
> 
> Given that the paper you mention seems to use Aslak Grinstead's code, which was based on Torrence & Compo 1998, I believe you can achieve the results you want by playing with the frequency vector.
> 
> You can use [this function](https://pyleoclim-util.readthedocs.io/en/latest/utils/introduction.html#pyleoclim.utils.wavelet.freq_vector_scale) to generate a frequency (scale) vector with the resolution you want and then pass it to `Series.wavelet_coherence()` as the `freq` argument. We show something similar in [this tutorial](http://linked.earth/PyleoTutorials/notebooks/L2_wavelet_analysis.html#customizing-the-frequency-range) though this is not exactly what you want. All you need to do to access the function I mentioned is `from pyleoclim.utils.wavelet import freq_vector_scale`
> 
> then you'll be on your way. Please let us know what you get!

Well, thank you for your kind guidance!

I utilize the method `freq_vector_scale` following your teach, and I get the similar result as before. The difference is that, the scales number is decreased, which is what I want.

However, I'm confused that my result is still low-energy and the significant result is less than the result in paper. And when I set the confidence area not to show, I find my arrows is different compared with the paper, expect for the scales 8-16. I wonder if it could be the problem of the parameters from the function or others. 

In addition, I find that the COI in my result is not complete. How can I complete it? 
Besides, when I set the `freq`, I find the order is reversed , like this, 

<img width="406" alt="138dc3987131253d6b9797591da08d2" src="https://github.com/user-attachments/assets/b6b48dd1-2612-4a30-b72d-1db62d2481a9">

and I need change it to order. Otherwise, it appears error when I use `coh=pv_series.wavelet_coherence(SWS_series,freq=freq)`. And the error shows, `ValueError: negative dimensions are not allowed`.

This is my new result.
<img width="773" alt="cc580bcbfe8008197d4720b1f143ca3" src="https://github.com/user-attachments/assets/0d6bbc87-e879-437a-8a53-86d040173d62">

**Comment by CommonClimate** [comment]
It's not easy reproducing your graph exact, so once PR #635 is incorporated (should be a few minutes), can you please run this again and make sure you are getting the results you should?
