### ISSUE TITLE
even/uneven spaced

### ISSUE THREAD

**Issue by SHEN-Cheng** [LinkedEarth/Pyleoclim_util#624]
Hi,

I've encountered a discrepancy regarding the spacing of my data in Pyleoclim. Specifically, when running the Welch method for spectral analysis, I'm receiving the error:

![image](https://github.com/user-attachments/assets/a3a0ff8b-54ac-4043-9649-9904e271124a)
![image](https://github.com/user-attachments/assets/3cf16ae3-026b-410c-b84d-5c5b43541009)

Prior to running the analysis, I verified that my data was evenly spaced, with the results confirming it as such. However, despite this, the error persists.

For reference, I’ve attached my data file (hourly wind speed data) here:
[brookhaven.hourly.10m.zip](https://github.com/user-attachments/files/17700530/brookhaven.hourly.10m.zip)

Thanks for looking into this! Any insights on why this might be occurring would be greatly appreciated.

**Comment by alexkjames** [comment]
Hi Shen,

Could you provide code that reproduces how you load your series object? In this case that appears to be your `data` variable. That would be a huge help to us in pinpointing this issue. Also, if you could provide your pyleoclim version, that would be useful as well (you can find this by running pyleoclim.__version__ in your notebook).

Thanks!

**Comment by SHEN-Cheng** [comment]
> pyleoclim.**version**

Sure, please see my code below:

```
brook_10m = xa.open_mfdataset(folder+"brookhaven.hourly.10m.nc").windagl10S1

brook_10m_pyleo = pyleo.Series(time = brook_10m.time, value = brook_10m, label = 'Brookhaven',
                  time_name = 'Time', value_name = '10 m wind speed',dropna =False,
                  time_unit='10 minute',value_unit = 'm s$^{-1}$', verbose=True)   
```

`brook_10m_pyleo.is_evenly_spaced()`

Return "True"

```
data=brook_10m_pyleo

data.standardize().spectral(method='welch').plot()
```

Returned:
---------------------------------------------------------------------------
```
ValueError                                Traceback (most recent call last)
Cell In[25], line 3
      1 data=brook_10m_pyleo
----> 3 data.standardize().spectral(method='welch').plot()

File ~/miniforge3/envs/mamba/lib/python3.12/site-packages/pyleoclim/core/series.py:3041, in Series.spectral(self, method, freq, freq_kwargs, settings, label, scalogram, verbose)
   3033     res = Results(amplitude=scalogram.amplitude, coi=scalogram.coi,
   3034                   freq=scalogram.frequency, time=scalogram.time,
   3035                   scale=scalogram.wave_args['scale'],
   3036                   mother=scalogram.wave_args['mother'],
   3037                   param=scalogram.wave_args['param'])
   3038     args['cwt'].update({'cwt_res':res})
-> 3041 spec_res = spec_func[method](self.value, self.time, **args[method])
   3042 if type(spec_res) is dict:
   3043     spec_res = dict2namedtuple(spec_res)

File ~/miniforge3/envs/mamba/lib/python3.12/site-packages/pyleoclim/utils/spectral.py:199, in welch(ys, ts, window, nperseg, noverlap, nfft, return_onesided, detrend, sg_kwargs, gaussianize, standardize, scaling, average)
    197 check = is_evenly_spaced(ts)
    198 if check == False:
--> 199     raise ValueError('For the Welch method, data should be evenly spaced')
    200 # preprocessing
    201 ys = preprocess(ys, ts, detrend=detrend, sg_kwargs=sg_kwargs,
    202            gaussianize=gaussianize, standardize=standardize)

ValueError: For the Welch method, data should be evenly spaced
```

The pyleoclim version is **1.1.0**

**Comment by alexkjames** [comment]
Ah I see, this is an error handling issue on our part. We'll adjust the code to provide a clearer error message.

You've set `drop_na=False` when you create your series. This means that, while your series is evenly spaced, the data contains empty values (nans). When the spectral method is called, it automatically drops those nans, resulting in an unevenly spaced series. In order for this to run properly, you'll need to first drop the nans in your series, then make sure it's evenly spaced. I would suggest setting `drop_na=True` in your series initialization, but you could also do something like this:

```
data=brook_10m_pyleo

value, time = pyleo.utils.tsbase.dropna(data.value, data.time)
data_clean = data.copy()
data_clean.value = value
data_clean.time = time
```

I also note that you're using a time unit that pyleoclim doesn't recognize, `10_minutes`. Additionally, your time values are very large. This is may cause problems when you try to plot, as pyleoclim won't know how to properly set up the x axis. I found that by passing `xticks = [1e12,1e13,1e14,1e15,1e16,1e17,1e18]` when calling `psd.plot` I was able to bypass the problem, but you may want to consider playing with the units your data are using, as currently you'll be stress testing some of pyleoclim's functionalities.

**Comment by SHEN-Cheng** [comment]
> (data.value, data.time)

Hi Alex,

Thank you for your suggestion, I would say the tsbase and clean operation is much convenient than the interploation after droping the nan values, as I just noticed the interpolation would bring some negetive wind speed values which is not realistic in my case.

A one quick question, could you please give more details on the tsbase in your command?

**Comment by alexkjames** [comment]
Hi Shen,

I would be curious to see how you are achieving negative wind speed values using interpolation. If your values are all positive before interpolation, they should be positive after interpolation. After all, if you're using our default settings, interpolation values should not be able to exceed the original bounds of your data. A quick test on my end suggests that this is true for your dataset as well, as after dropping nans and interpolating, I do not observe values below zero. Perhaps you're referring to having negative values after standardization? While non-physical, this won't affect the results of spectral analysis.

Regardless, if you wish to use the `welch` or `mtm` methods,  you'll need to apply some kind of interpolation and/or binning scheme to your data after you drop your nans in order to ensure that the resulting timeseries is evenly spaced. Applying `clean_ts` as I did in my example will produce an identical series to setting `drop_na=True` when you create your series initially. If you do not wish to interpolate at all, you'll be restricted to using `wwz` or `lomb_scargle`. These methods are slower, but are designed to work with unevenly spaced data, though they carry their own sets of biases. I suggest referring to our [tutorial on spectral analysis](http://linked.earth/PyleoTutorials/notebooks/L2_spectral_analysis.html) for further reading on this.

Further info on tsbase, a subsection of our utility functions, can be found [here](https://pyleoclim-util.readthedocs.io/en/latest/utils/introduction.html#module-pyleoclim.utils.tsbase). 

Let me know if you have any more questions.

**Comment by CommonClimate** [comment]
I'll add that there is a reason `dropna=True` is the default when instantiating a Series ; it's precisely to prevent this sort of issue, and why it had not appeared before. Now, were are grateful that your misadventure led us to find a bug in our error handling, but in the feature you might want to think twice about overriding defaults!

I second @alexkjames 's comment about time units. '10 minute' is not a recognized unit. This is what is currently covered:
```
MATCH_A  = frozenset(['y', 'yr', 'yrs', 'year', 'years'])
MATCH_KA = frozenset(['ka', 'ky', 'kyr', 'kyrs', 'kiloyear', 'kiloyr', 'kiloyrs'])
MATCH_MA = frozenset(['ma', 'my','myr','myrs'])
MATCH_GA = frozenset(['ga', 'gy', 'gyr', 'gyrs'])
```

 If no match can be found, the code assume time to be in years CE. We could accommodate other units (e.g. days, months) using pandas functionalities, but pandas interoperability is currently limited to a bug on their side with non-nanosecond dtypes, which has been extant for months and has an uncertain resolution timeline.

**Comment by SHEN-Cheng** [comment]
> `wwz`

I have converted the wind resolution to hourly, but it apperas there is no match was found in the default units.

**Comment by SHEN-Cheng** [comment]
> I'll add that there is a reason `dropna=True` is the default when instantiating a Series ; it's precisely to prevent this sort of issue, and why it had not appeared before. Now, were are grateful that your misadventure led us to find a bug in our error handling, but in the feature you might want to think twice about overriding defaults!
> 
> I second @alexkjames 's comment about time units. '10 minute' is not a recognized unit. This is what is currently covered:
> 
> ```
> MATCH_A  = frozenset(['y', 'yr', 'yrs', 'year', 'years'])
> MATCH_KA = frozenset(['ka', 'ky', 'kyr', 'kyrs', 'kiloyear', 'kiloyr', 'kiloyrs'])
> MATCH_MA = frozenset(['ma', 'my','myr','myrs'])
> MATCH_GA = frozenset(['ga', 'gy', 'gyr', 'gyrs'])
> ```
> 
> If no match can be found, the code assume time to be in years CE. We could accommodate other units (e.g. days, months) using pandas functionalities, but pandas interoperability is currently limited to a bug on their side with non-nanosecond dtypes, which has been extant for months and has an uncertain resolution timeline.

I have converted the wind resolution to hourly, but it apperas there is no match was found in the default units.

**Comment by SHEN-Cheng** [comment]
> In the meantime, you just have to be aware that you may run into issues with your units. Generally speaking, so long as the values on your time axis are sensible (e.g. not in the septendecillions, as they are by default in the data you shared), you should be ok to use most of our functionalities, so long as you take care to make sure your results look sensible. However, you may wish to convert your units to use annual resolution while you compute spectra and whatnot, and convert them back before plotting. This would be the most robust approach.

Thank you for the suggestion, I have emplyed it in my current jupyter notebook. I hope a more higher resolution feature will come soon.
