### ISSUE TITLE
Graphic identity

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#66]
It's important for our plots to have a distinct look and feel.
To me that involves two things:
- using a Matplotlib style (either [existing](https://matplotlib.org/gallery/style_sheets/style_sheets_reference.html) or custom) throughout, instead of doing so on a function by function basis.
- despining most (all?) plots. 

Currently our style is a bit of a mish-mash, so we need to get coherent. What style do you prefer? I'm pretty happy with the new matplotlib default, with ggplot a close second.  

Another consideration is customizability: it's essential to have sensible defaults, but it should be easy for users to override that if they have a preferred style.  I think this can be done easily by explaining in the documentation that the package sets its own Matplotlib style, but explain how users can override that in one line of code.

**Comment by CommonClimate** [comment]
For instance: "Pyleoclim makes use of the ggplot style, so sets `plt.style.use('ggplot')` upon loading. To override to 'bmh', say, simply type `plt.style.use('bmh')` at the top of your script/notebook, right after `import pyleoclim as pyleo`.

**Comment by khider** [comment]
@fzhu2e  Can be done through the new api upper function: [Issue#60](https://github.com/LinkedEarth/Pyleoclim_util/issues/60)

**Comment by khider** [comment]
@fzhu2e Has this also been addressed by the weekend push?

**Comment by fzhu2e** [comment]
> @fzhu2e Has this also been addressed by the weekend push?

Yes, I think so.

**Comment by khider** [comment]
Closing
