### ISSUE TITLE
SSA method for enhancing SNR

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#70]
1. Provide notebook example
2. Integrate into Pyleoclim

**Comment by CommonClimate** [comment]
Yes to 1. However, I don't know of a general rule to integrate it into Pyleoclim, as this is quite a subjective game, and I am afraid that subsuming it within a spectral analysis call would hide to many assumptions away from the user. The blacker the box, the murkier the interpretation, and the wilder the resulting claims in the literature.

**Comment by khider** [comment]
I would say leave the main spectral function alone. For the workflows, we can have the default to "do not use". If turn on, we put a warning and dump the assumptions.

**Comment by CommonClimate** [comment]
SSA method now operational, thanks to @fzhu2e, and I wrote a notebook to illustrate its basic use, available at https://github.com/LinkedEarth/LiPDbooks/blob/master/notebooks/Singular%20Spectrum%20Analysis.ipynb
