### ISSUE TITLE
JetStream deployment

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#72]
Installation issues are real (particularly for Windows users, for whom Anaconda is hit or miss, and Basemap is still a major issue). One idea to circumvent them is to run our notebooks on 
JetStream (https://jetstream-cloud.org). First, we need to check that it is feasible. Can someone give it a try?

**Comment by fzhu2e** [comment]
It seems that the account is free, but we need to apply for the resource by submitting a request. The details can be found here in the section [Apply for an XSEDE allocation](https://iujetstream.atlassian.net/wiki/spaces/JWT/pages/49184781/Jetstream+Allocations).

**Comment by CommonClimate** [comment]
No longer needed at this point. May get reactivated if need arises again.
