### ISSUE TITLE
Rearrange Pyleoclim modules

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#74]
Proposed change:
1. Wrapper module called workflow.py that will handle LiPD files directly and automate some of the decisions (as much as possible). 

Workflows would either allow for a LiPD object (dictionary) or for a user dictionary containing appropriate information as specified by function (e.g., time, value for Series).

2. Upper module api.py which would contain the functions that are most likely being used by a user to return either results, plots or text. Object-driven.

Can be used to create personal workflows. See Jupyter Notebook as example. These methods will be re-used in workflow.py

Classes to consider: 
- Series -> plot, hist, clean, correlation, causality, spectral, wavelet, wavelet coherence, generate surrogate of the series, filter, PCA, SSA, stats, interpolation (interp/bin), standardize, annualize (with lots of error checks), 
- Output of spectral becomes a PSD object -> plot
- Output of wavelet becomes a scalogram object-> plot
- Output of coherence becomes Coherence object->plot
- Ens class -> takes a list of series objects, plot
- Chron obj -> generate ensembles
- LiPD object -> map, summaryplots, then send to other objects
- MultipleSeries -> list of series/ens objects; correlation with FDR, PCA, plot (stack plot)

3. Lower modules, which contains base methods. Need to concatenate as follows:

- examples.py - example data
- lipdutils.py
- map + plot + summaryplots -> visualization and deal with [issue #66](https://github.com/LinkedEarth/Pyleoclim_util/issues/66)
- rbchron -> age model
- spectral, stats, timeseries -> analysis.py

**Comment by fzhu2e** [comment]
Files have been reorganized in this [commit](https://github.com/LinkedEarth/Pyleoclim_util/commit/d7f0bba70cfd61787aa169d7e2d982efa87f9f3a):
map.py + plot.py + summparyplots.py -> visualization.py
spectral.py, stats.py, timeseries.py -> analysis.py

**Comment by khider** [comment]
rbchron module renamed to age model in this [commit](https://github.com/LinkedEarth/Pyleoclim_util/commit/56be0ab8da7e2c8d479085d4e534c837ca2f7e6f)

**Comment by khider** [comment]
Need separate classes to handle LiPD objects and LiPDTimeseries objects

**Comment by khider** [comment]
Rearranging of the modules is complete. Need more classes in  ui.py to accommodate LiPD files/
