### ISSUE TITLE
Create stack plot for multiple timeseries 

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#75]
https://github.com/nickmckay/GeoChronR/blob/master/vignettes/PlotTimeseriesStack.Rmd

**Comment by khider** [comment]
Function is executing but not returning proper plots. Will fix in future release.

**Comment by fzhu2e** [comment]
Addressed in commit 7d87b44.
A notebook demo: https://github.com/LinkedEarth/Pyleoclim_util/blob/Development/example_notebooks/stack_plot.ipynb
