### ISSUE TITLE
Need method arguments in Series.summary_plot()

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#84]
The current `Series.summary_plot()` does not take any method argument, and the default `wwz` will be used to calculate PSD and scalogram if `psd` and `scalogram` not precalculated and provided.

We need to add arguments like `spec_method`, `spec_kwargs`, `wave_method`, `wave_kwargs` for `Series.summary_plot()` to allow for other methods than WWZ.

**Comment by khider** [comment]
This [issue](https://github.com/LinkedEarth/Pyleoclim_util/issues/135) needs to be addressed before enabling cwt
