### ISSUE TITLE
Align parameters for MutipleSeries.spectral and Series.Spectral

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#86]
**Is your feature request related to a problem? Please describe.**
Parameters between the two functions are different (confusing).

**Describe the solution you'd like**
Agree on the set of parameters that should be exposed and align the two

**Describe alternatives you've considered**
leave as is

**Additional context**
NA

**Comment by fzhu2e** [comment]
Fixed in commit 1644582.
