### ISSUE TITLE
MultipleSeries.wavelet() only allows for wwz

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#87]
**Is your feature request related to a problem? Please describe.**
MultipleSeries.wavelet() only allows for wwz but the single series method allows for both. Confusing for a user

**Describe the solution you'd like**
Align both methods

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by fzhu2e** [comment]
Fixed in commit 133478d.
