### ISSUE TITLE
LiPD usr_path is now invalid

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#88]
**Describe the bug**
Path given is invalid for LiPD files
May have to do with correction to allow for relative path pushed by @fzhu2e 

**To Reproduce**
import pyleoclim as pyleo
d=pyleo.Lipd(usr_path='http://wiki.linked.earth/wiki/index.php/Special:WTLiPD?op=export&lipdid=MD982176.Stott.2004')
Disclaimer: LiPD files may be updated and modified to adhere to standards

Error: Path given is invalid
Finished read: 0 records

**Expected behavior**
To load the LiPD file appropriately

**Screenshots**
See error above

**Desktop (please complete the following information):**
 Pyleoclim version 0.5.0

**Comment by fzhu2e** [comment]
Fixed in commit 10dad2edd86bce3fbab8813182c9f9d34b538a82
If `usr_path` starts with "http", "https", or "ftp", it will be treated as a URL; otherwise, a local path
