### ISSUE TITLE
Suggestion: set `standardize=False` as default for spectral methods in spectral.py

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#93]
**Is your feature request related to a problem? Please describe.**
The current default setting of `standardize` for the spectral methods in spectral.py is `True`, which will change the absolute amplitude of the PSD. Sometimes the users might not want this but they are unaware of this argument doing the work in the background.

**Describe the solution you'd like**
Set `standardize=False` so that the input data will be untouched.
It's now super easy to perform `Series.standardize()` if the users need it.

**Comment by CommonClimate** [comment]
are we sure nothing will break if we make the switch? If so, I support the change.

**Comment by khider** [comment]
Agreed. But it will break code. Let's follow best practice and have a warning on these functions on the next release and then change it.

**Comment by khider** [comment]
Implemented in version 0.5.1
