### ISSUE TITLE
Rename package to "pyleoclim"

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#94]
**Is your feature request related to a problem? Please describe.**
Pyleoclim_util is verbose and off-putting. 

**Describe the solution you'd like**
should be called pyleoclim (all lowercase)

**Describe alternatives you've considered**
no change

**Comment by khider** [comment]
You mean the GitHub repo? The package is called pyleoclim

**Comment by CommonClimate** [comment]
then why do the repo (and readthedocs) have a different name?

**Comment by khider** [comment]
Doing so will break links in notebooks and docs.
