### ISSUE TITLE
More user-friendly "Getting Started" section

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#95]
**Is your feature request related to a problem? Please describe.**
The current "Getting Started" section of the [github page](http://linkedearth.github.io/Pyleoclim_util/) is a stub. Only contains installation, which is a small part of the battle.
 
**Describe the solution you'd like**
Include information on example notebooks, current LiPDbooks, and links to the "readthedocs" documentation. 

**Describe alternatives you've considered**
keep as is

**Comment by khider** [comment]
Done in version 0.5.1
