### ISSUE TITLE
Missing diagram in the UI tutorial notebook

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/Pyleoclim_util#96]
**Describe the bug**
 the UI tutorial notebook ends with "To summarize, below is the hierarchy of the UI of Pyleoclim:", followed by what should be a diagram, but currently isn't loading

**To Reproduce**
1. Go to https://github.com/LinkedEarth/Pyleoclim_util/blob/master/example_notebooks/pyleoclim_ui_tutorial.ipynb
2. Scroll to the bottom
3. See error

**Expected behavior**
A diagram should be there
**Desktop (please complete the following information):**
 - MacOS 10.15.4
 - Safari Version 13.1 (15609.1.20.111.8)

**Additional context**

**Comment by fzhu2e** [comment]
Fixed in a commit to the Development branch: https://github.com/LinkedEarth/Pyleoclim_util/blob/Development/example_notebooks/pyleoclim_ui_tutorial.ipynb ; waiting for merge

**Comment by khider** [comment]
Will get merged in next master commit
