### ISSUE TITLE
Inconsistent number of return variables for `tsutils.bin_values()` in `Series.bin()`

### ISSUE THREAD

**Issue by fzhu2e** [LinkedEarth/Pyleoclim_util#99]
**Describe the bug**
Inconsistent number of return variables for tsutils.bin_values() in Series.bin():
In `Series.bin()`, it calls ` x_mod, v_mod = tsutils.bin_values(self.time,self.value,**kwargs)`,
while `tsutils.bin_values()` returns four variables `bins, binned_values, n, error`.

Suggest to use a dictionary as the return of `tsutils.bin_values()`, and then use another dictionary in `Series.bin()` to store the output, so that it's flexible.

**Comment by khider** [comment]
Fixed in [this commit](https://github.com/LinkedEarth/Pyleoclim_util/commit/dc1c53efca32b1ffeff5b6f5ea0e1aa6cff265d9)
